(function (root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.MwiGuildCreditLocalization = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const STRINGS = {
    "zh-CN": {
      unknownItem: "未知物品",
      priceReferenceA: "左一",
      priceReferenceATitle: "左一：最低出售价，可立即买入",
      priceReferenceB: "右一",
      priceReferenceBTitle: "右一：最高收购价；低于可交易区间的报价会忽略",
      marketItem: "在市场中查看{item}",
      updateChecking: "当前版本 v{current} · 最新版本：检查中...",
      updateAvailable: "当前版本 v{current} · 最新版本 v{latest} · 发现新版本",
      updateNow: "立即更新",
      updateLatest: "当前版本 v{current} · 最新版本 v{latest} · 已是最新",
      updateUnavailable: "当前版本 v{current} · 最新版本：暂时无法读取",
      shrineForce: "力量神龛",
      shrineTempo: "节奏神龛",
      shrineSpirit: "精神神龛",
      shrineRarity: "稀有神龛",
      shrineScholar: "学者神龛",
      domainLife: "生活",
      domainCombat: "战斗",
      shrineWithDomain: "{shrine}（{domain}）",
      guildTargetApplied: "已按当前公会神龛等级设定{domain}计划，共 {count} 项需要升级。",
      guildTargetComplete: "当前已达到最大等级（{domain}）。",
      plansCleared: "已清空全部神龛升级计划。",
      level: "{level} 级",
      targetButtonReady: "按每座对应公会神龛的当前等级批量设定目标",
      targetButtonMissing: "尚未读取完整的公会神龛建筑等级：{missing}",
      targetSummary: "{domain} {count}/{total}{missing}",
      targetSummaryMissing: "（未识别：{missing}）",
      shrineLevelsRead: "公会神龛等级已读取：{summaries}。",
      shrineLevelsReading: "正在读取当前公会神龛建筑等级…",
      shrine: "神龛",
      startLevel: "起始等级",
      targetLevel: "目标等级",
      removePlan: "移除此项",
      gold: "金币",
      guildTokens: "公会代币",
      noSnapshotEstimate: "未读取到公开市场快照，暂无法估算金币成本。",
      partialEstimatedCost: "预计成本（已定价部分）",
      estimatedTotalCost: "预计总成本",
      partialAfterInventory: "库存后缺口（已定价部分）",
      afterInventory: "库存后仍需",
      inventoryUnavailable: "未读取背包库存，缺口暂按 0 件库存计算。",
      noCreditPrice: "以下信用点暂无可用市场价格：{items}。",
      costSummary: "成本概览",
      inventoryAndMissing: "库存 {owned} · 缺 {missing}",
      inventory: "库存 {count}",
      inventoryNotRead: "库存未读取",
      inventoryCoveredNoExchange: "现有库存已覆盖，无需兑换",
      backpackInventory: "背包库存 {count}",
      notRead: "未读取",
      useGuildTokensForMissingCredits: "全部信用点使用公会代币",
      useGuildTokensForMissingCreditsHint: "快速选择或清除全部；也可在每张信用点卡片单独切换。",
      guildTokenCreditPlanActive: "缺少的信用点已全部按公会代币兑换计算。",
      guildTokenCreditPlanPartialActive: "已选择 {count} 种信用点按公会代币兑换计算。",
      guildTokenCreditPlanSummary: "其中 {count} 公会代币用于兑换信用点。",
      autoGuildTokenBudget: "自动兑换代币预算",
      autoGuildTokenBudgetHint: "按每枚公会代币的市场兑换价值从高到低分配。",
      autoGuildTokenBudgetAvailable: "本次最多可用 {count}",
      autoGuildTokenPlanSummary: "已按兑换价值自动分配 {count} 枚库存公会代币。",
      autoGuildTokenExchangeNeeds: "自动分配代币",
      autoGuildTokenCoverage: "覆盖 {count} 信用点",
      optimalItemCreditMode: "最优物品",
      guildTokenCreditMode: "公会代币",
      creditExchangeModeTitle: "当前使用{mode}兑换；点击切换。",
      guildTokenExchangeNeeds: "代币兑换需",
      optimalExchangeNeeds: "最优兑换需",
      exchangeRate: "{items} → {credits}",
      itemQuantity: "{count} 个",
      creditQuantity: "{count} 点",
      optimalExchangeUnavailable: "最优兑换：暂无可用市场价格",
      requiredThisTime: "本次所需",
      noGuildRules: "未读取到神龛升级规则。请刷新游戏页面后重新打开公会。",
      noUpgradePlans: "当前没有神龛升级计划。",
      noUpgradePlansHint: "点击“添加神龛”，或使用上方按钮按当前公会等级填充。",
      allBuffsMaxed: "当前所有神龛增益均已满级。",
      noUpgradeMaterials: "当前没有需要计算的神龛升级材料。",
      missingLevelCost: "缺少 {level} 级升级成本数据。",
      invalidLevels: "起始等级或目标等级无效。",
      mergedUpgradePlans: "已合并 {count} 项神龛升级的材料成本。",
      unknownCurrentLevels: "未读取当前神龛等级，已按 0 级开始；请确认或手动调整“起始等级”。",
      snapshotFailed: "公开市场快照读取失败，暂未估算金币成本。",
      panelTitle: "公会助手",
      creditValue: "信用点性价比",
      creditValueHint: "按目标数量比较公开市场成本，首项为当前最优兑换。",
      shrineUpgrade: "神龛升级",
      guildConstruction: "公会建设",
      panelViewOrder: "页签顺序",
      moveViewLeft: "将当前页签左移",
      moveViewRight: "将当前页签右移",
      interfaceSettings: "设置",
      interfaceSettingsHint: "调整一键填充范围和插件页面；修改会立即在本机生效。",
      openInterfaceSettings: "打开设置",
      closeInterfaceSettings: "关闭设置",
      shrineAutofillRange: "一键填充范围",
      shrineAutofillRangeHint: "取消勾选后，一键填充不会新增或更新该神龛；已有计划不会删除。",
      settingsShrinesLoading: "正在读取可配置的公会神龛…",
      settingsShrinesEmpty: "已读取游戏数据，但没有可配置的公会神龛。",
      interfaceVisibility: "界面",
      showConstructionView: "显示公会建设页面",
      showConstructionViewHint: "关闭后隐藏页签；施工计划仍会保留，可随时重新开启。",
      settingsSaved: "设置已保存。",
      settingsSaveFailed: "设置已生效，但未能保存；刷新页面后可能恢复。",
      constructionViewShown: "已显示公会建设页面。",
      constructionViewHidden: "已隐藏公会建设页面；施工计划仍已保留。",
      constructionReadOnly: "管理员规划工具 · 只计算，不会执行建筑升级",
      guildPointBudget: "可用公会点数",
      manualBudget: "手工预算",
      budgetOptional: "留空使用游戏当前可用点数",
      invalidGuildPointBudget: "请输入不小于 0 的整数。",
      guildPointTrend: "每周公会点数",
      guildPointOverview: "公会点数与预算",
      guildPointStatisticsHeading: "点数统计与历史",
      buildingCatalogCurrentLevel: "当前 {current} 级",
      buildingCatalogUnknownPlannedLevel: "未读取 · 按 {current} → {target} 级规划",
      buildingCatalogPlannedLevel: "{current} → {target} 级 · 已加入",
      buildingCatalogUnknownLevel: "未读取 · 按 0 级规划",
      guildPointPlanningHeading: "建设预算",
      guildPointStartingBalance: "自定起始点数",
      guildPointFollowBalance: "跟随游戏余额",
      guildPointStartingBalanceHint: "选填；清空后使用当前可用点数。",
      guildPointTrendHint: "按累计公会点数增量自动记录，建筑消费不会影响统计。",
      guildPointAutoSaved: "自动保存",
      guildPointSavedSnapshot: "已保存快照",
      currentAvailableGuildPoints: "当前可用",
      currentWeekGuildPoints: "本周试炼点数",
      predictedCurrentWeekGuildPoints: "本周预测点数",
      latestWeeklyGuildPoints: "最近完整周获得",
      weeklyGuildPointGrowth: "环比增长",
      guildPointEstimatedGrowth: "预计周增长速度",
      nextWeekGuildPointForecast: "下周预测",
      guildPointHistoryUnavailable: "尚未读取公会点数；打开公会页面后会自动建立本机基线。",
      guildPointHistoryBaseline: "已建立累计点数基线；下一次周奖励到账后将生成首条周记录。",
      guildPointForecastNeedsHistory: "已自动保存周记录；至少需要连续 2 周数据才能预测。",
      guildPointForecastColdStart:
        "此前 {count} 周平均 {average} 点，本周已获 {current} 点；按历史中点拟合，每周约增长 {growth} 点，下周预计 {forecast} 点。本周未结束时结果仍会变化。",
      guildPointForecastMethod: "按最近连续 {count} 个完整周的平均增量预测。",
      guildPointForecastEstimatedMethod: "按最近 {count} 个完整周的平均增量预测，其中包含自动补充记录。",
      guildPointHistoryConflict: "历史周点数合计超过游戏累计值，已停止预测。请检查手动记录或重置周记录。",
      guildPointForecastWeeks: "预测回看周数",
      guildPointForecastWeeksHint: "只使用最近连续的完整周。",
      increaseGuildPointForecastWeeks: "增加 1 周预测回看范围",
      decreaseGuildPointForecastWeeks: "减少 1 周预测回看范围",
      guildPointPlanningWeeks: "规划周数",
      guildPointPlanningOptions: "预测设置",
      guildPointPlanningWeeksHint: "0 表示仅使用当前点数；大于 0 时将预测周产出加入可用预算。",
      increaseGuildPointPlanningWeeks: "增加 1 周规划时间",
      decreaseGuildPointPlanningWeeks: "减少 1 周规划时间",
      guildPointPlanningCurrentOnly: "仅当前点数",
      guildPointWeekCount: "{count} 周",
      guildPointWeekWithDate: "第 {count} 周（{date}）",
      guildPointPlanningNeedsBalance: "尚未读取当前可用点数。",
      guildPointPlanningNeedsForecast: "已保留当前点数预算；历史不足或冲突，暂无法加入未来周。",
      guildPointPlanningBudgetCurrent: "规划预算：当前 {total} 点。",
      guildPointPlanningBudgetProjected: "规划预算：{current} + {weeks} 周 × {weekly} = {total} 点。",
      recentGuildPointHistory: "最近周记录",
      manualGuildPointWeek: "周次",
      manualGuildPointEarned: "该周获得点数",
      manualGuildPointEarnedForWeek: "{week} 获得的公会点数",
      guildPointHistorySource: "来源",
      saveManualGuildPointHistory: "保存整张表",
      manualGuildPointHint:
        "灰色占位数为自动估算。修改游戏追踪值需先确认警告。清空后保存：原追踪值为 0 时改为自动补充，非零时恢复原值；直接填写 0 则保留零值。当前周仅供查看。",
      manualGuildPointHistoryEmpty: "尚无已结束的试炼周可填写。",
      guildPointManualWeekOption: "{week} 开始",
      guildPointSourceTracked: "游戏追踪",
      guildPointSourceTrackedEditing: "待保存更正",
      guildPointSourceManual: "手动录入",
      guildPointSourceManualOverride: "手工覆盖追踪值",
      guildPointSourceEstimated: "自动补充",
      guildPointSourceEmpty: "待填写",
      guildPointSourceCurrent: "游戏追踪中",
      guildPointSourceCurrentEstimated: "本周预测",
      guildPointSourceCurrentPending: "本周未开始",
      guildPointSourceCurrentUnavailable: "尚未读取",
      currentGuildPointWeek: "当前周",
      removeManualGuildPointWeek: "删除 {week} 的手动记录",
      manualGuildPointWeekSaved: "历史公会点数已保存，缺失周已重新自动补充。",
      manualGuildPointWeekTracked: "该周已有游戏真实追踪记录，不能被手动值覆盖。",
      editTrackedGuildPointWeek: "修改 {week} 的游戏追踪值",
      editTrackedGuildPointWeekShort: "修改",
      trackedGuildPointEditWarningTitle: "要覆盖游戏追踪值吗？",
      trackedGuildPointEditWarningBody:
        "{week} 的 {points} 点来自游戏追踪。继续后可以用手工值更正；这只会影响插件的历史统计、预测和施工估算，不会修改游戏内数据。",
      trackedGuildPointEditWarningHint: "清空后保存：原追踪值为 0 时改为自动补充，非零时恢复原值。",
      cancelTrackedGuildPointEdit: "取消",
      confirmTrackedGuildPointEdit: "继续修改",
      manualGuildPointWeekInvalid: "请选择已结束的试炼周，并输入不小于 0 的整数。",
      manualGuildPointWeekRemoved: "手动历史记录已删除，空缺周已恢复为自动补充。",
      manualGuildPointHistorySaved: "历史公会点数表已保存，留空的周将继续自动估算。",
      constructionEta: "施工计划预计",
      constructionEtaNoPlan: "尚无计划",
      constructionEtaNoPlanHint: "添加建筑后估算完成时间。",
      constructionEtaNeedsBalance: "尚未读取当前可用点数，请手工填写预算。",
      constructionEtaNeedsForecast: "积累 2 个连续完整周后估算完成时间。",
      constructionEtaHistoryConflict: "历史点数与游戏累计值冲突，暂停估算。",
      constructionEtaNoGrowth: "预测周产出为 0，暂时无法估算。",
      constructionEtaCovered: "当前点数已覆盖",
      constructionEtaCoveredHint: "无需等待新的周点数即可完成计划。",
      constructionEtaWeeks: "约 {count} 周",
      constructionEtaDetail: "按每周约 {points} 点，尚缺 {shortfall} 点。",
      constructionEtaDetailEstimated: "暂按历史回填每周约 {points} 点，尚缺 {shortfall} 点。",
      exportGuildPointHistory: "导出周记录 CSV",
      resetGuildPointHistory: "重置周记录",
      resetGuildPointHistoryConfirm: "确定重置当前角色的公会点数周记录吗？施工计划不会被删除，此操作无法撤销。",
      guildPointHistoryReset: "当前角色的周记录已重置，并从当前累计点数重新建立基线。",
      guildPointCsvWeekStart: "周开始时间",
      guildPointCsvEarned: "获得公会点数",
      guildPointCsvStatus: "记录状态",
      guildPointCsvComplete: "完整周",
      guildPointCsvTracking: "本周追踪中",
      guildPointCsvManual: "手动录入",
      guildPointCsvEstimated: "自动补充",
      guildPointCsvFileName: "银河奶牛-公会点数周记录.csv",
      plannedSpend: "计划消耗",
      plannedUpgrades: "计划升级",
      affordableUpgrades: "预算可完成",
      remainingPoints: "预算剩余",
      overBudgetBy: "超出预算",
      constructionPlanScale: "{buildings} 座 · {steps} 级",
      constructionBudgetEmptySummary: "添加建筑后显示预算可执行范围。",
      constructionNoBudgetSummary: "未设置预算 · 共 {total} 次升级",
      constructionBudgetAllFit: "预算覆盖全部 {total} 次升级。",
      constructionBudgetStopsBefore: "可完成 {affordable}/{total} 次；下一项 {building} {from}→{to} 还差 {count}",
      buildingCatalog: "建筑目录",
      buildingCatalogHint: "选择建筑加入计划；可连续添加多座。",
      addBuilding: "添加建筑",
      closeBuildingPicker: "收起建筑目录",
      buildingCategoryFilter: "建筑分类",
      buildingCategoryAll: "全部",
      buildingCategoryCore: "基础",
      buildingCategoryLife: "生活",
      buildingCategoryCombat: "战斗",
      buildingCategoryShrine: "神龛",
      searchBuildings: "搜索建筑",
      currentLevel: "当前等级",
      buildingPlanCost: "计划成本",
      buildingEditor: "建筑计划编辑器",
      selectBuildingPrompt: "请选择一座建筑。",
      buildingMaxLevel: "已满级",
      notPlanned: "未计划",
      buildingTileLabel: "{building}，当前 {current} 级，目标 {target}",
      buildingTileAddLabel: "添加 {building}，当前 {current} 级",
      buildingTileDefaultZeroLabel: "添加 {building}；未读取到等级，按 0 级规划",
      buildingTilePlannedLabel: "定位到 {building} 的施工行，目标 {target} 级",
      buildingTileMaxLabel: "{building} 已满级，不能加入计划",
      cancel: "取消",
      buildingAddedToPlan: "已将 {building} 加入施工计划。",
      buildingRemovedFromPlan: "已将 {building} 移出施工计划。",
      buildingTargetUpdated: "{building} 的目标已更新为 {target} 级。",
      buildingPlansReconciled: "已按实时等级调整 {adjusted} 项计划，并移除 {removed} 项已完成计划。",
      addOneLevel: "加 1 级",
      addFiveLevels: "加 5 级",
      removeBuildingPlan: "移出计划",
      movePlanUp: "将 {building} 提前一位",
      movePlanDown: "将 {building} 延后一位",
      constructionQueue: "施工计划",
      constructionQueueHint: "按建筑分组排序；逐级费用默认收起。",
      constructionQueueDragHint: "拖动手柄排序，也可使用提前、延后按钮；键盘可按 Alt 加上下方向键。",
      dragConstructionPlan: "调整 {building} 的施工顺序",
      constructionQueueEmptyTitle: "施工计划为空",
      constructionQueueEmpty: "选择“添加建筑”开始规划。",
      constructionBudgetCutoff: "预算截止线 · 剩余 {count}",
      constructionGroupBudgetCutoff: "预算可升至 {level} 级 · 下一等级还差 {count}",
      constructionBudgetUnbudgeted: "待预算",
      constructionWithinBudget: "预算内",
      constructionPartiallyWithinBudget: "部分预算内",
      constructionOverBudget: "超预算",
      constructionSummary: "{buildings} 座建筑 · {steps} 次升级",
      constructionPlanRowMeta: "第 {position} 项 · {start}→{target} · {count} 次升级",
      buildingTargetLabel: "{building} 的目标等级",
      increaseBuildingTarget: "将 {building} 的目标提高 {count} 级",
      expandBuildingSteps: "展开 {building} 的逐级费用",
      collapseBuildingSteps: "收起 {building} 的逐级费用",
      removeBuildingFromPlan: "将 {building} 移出施工计划",
      buildingLevelsCoverage: "已读取 {known}/{total}",
      buildingLevelsPartialHint: "{unknown} 座建筑未读取到等级，已按 0 级处理。",
      missingBuildingCost: "{building} 缺少 {level} 级费用，未计入总成本。",
      moreConstructionActions: "更多施工计划操作",
      clearBuildingPlans: "清空施工计划",
      undoClearBuildingPlans: "撤销清空",
      copyBuildingPlan: "复制规划",
      exportBuildingCsv: "导出 CSV",
      buildingPlanCopied: "施工规划已复制。",
      buildingPlanCopyFailed: "无法写入剪贴板，请使用 CSV 导出。",
      noBuildingMatches: "没有符合筛选条件的建筑。",
      buildingPlanCleared: "已清空 {count} 项施工计划。",
      buildingPlanRestored: "已恢复 {count} 项施工计划。",
      buildingPlanReordered: "施工顺序已保存。",
      buildingPlanMovedToPosition: "{building} 已移至第 {position} 项，共 {total} 项。",
      constructionOrder: "顺序",
      fromLevel: "起始等级",
      toLevel: "目标等级",
      stepCost: "本级成本",
      cumulativeCost: "累计成本",
      buildingCsvFileName: "银河奶牛_公会建筑规划.csv",
      buildingGuildHall: "公会大厅",
      buildingBuildersHall: "建造者殿堂",
      buildingArchives: "档案馆",
      buildingTreasury: "金库",
      buildingSkillingEncampment: "生活营地",
      buildingWorkshop: "公会工作间",
      buildingForge: "公会锻造台",
      buildingLogShed: "公会木棚",
      buildingGarden: "公会花园",
      buildingDairyBarn: "公会奶牛棚",
      buildingKitchen: "公会厨房",
      buildingSewingParlor: "公会缝纫室",
      buildingBrewery: "公会冲泡坊",
      buildingLibrary: "公会图书馆",
      buildingLaboratory: "公会实验室",
      buildingMysticalStudy: "公会神秘研究室",
      buildingCombatEncampment: "战斗营地",
      buildingGym: "公会健身房",
      buildingDojo: "公会道场",
      buildingArcheryRange: "公会射箭场",
      buildingArmory: "公会军械库",
      buildingDiningRoom: "公会餐厅",
      buildingObservatory: "公会天文台",
      targetCredits: "目标信用点",
      increaseTargetCredits: "增加 100 目标信用点",
      decreaseTargetCredits: "减少 100 目标信用点",
      marketReference: "市场价格参考",
      priceReference: "价格参考",
      refreshEstimate: "刷新市场估算",
      maxItemUnitPricePrefix: "屏蔽单价超过",
      maxItemUnitPriceSuffix: "M 的物品",
      maxItemUnitPricePlaceholder: "不屏蔽",
      maxItemUnitPriceInput: "屏蔽单价超过多少 M 金币的兑换物品",
      increaseMaxItemUnitPrice: "增加 10M 屏蔽单价上限",
      decreaseMaxItemUnitPrice: "减少 10M 屏蔽单价上限",
      maxItemUnitPriceHint: "按当前左一或右一的单件市场价过滤；清空输入可关闭过滤",
      maxItemUnitPriceInvalid: "请输入大于 0 的 M 金额，例如 50",
      maxItemUnitPriceSaveFailed: "价格上限保存失败，本次会话仍然有效",
      waitingExchangeRules: "等待游戏兑换数据...",
      guildShrineBatchPlan: "按当前公会神龛等级批量规划",
      setGuildLifeTarget: "填充生活等级",
      setGuildCombatTarget: "填充战斗等级",
      guildAutofillAllExcluded: "所有{domain}神龛均已从一键填充中排除。",
      guildAutofillDomainExcluded: "当前没有参与一键填充的{domain}神龛；请在设置中至少勾选一项。",
      selectedUpgradePlanCount: "已选择 {count} 项升级计划",
      addShrine: "添加神龛",
      clearAll: "清空全部",
      guideEnable: "开启高亮指引",
      guideDisable: "关闭高亮指引",
      guideReady: "高亮指引已待命",
      guideReadyHint: "开启后会根据规划和实时库存标出下一步，不会自动操作。",
      guideNoPlans: "尚未添加神龛计划",
      guideNoPlansHint: "添加至少一项神龛升级后即可开始指引。",
      guideLoading: "正在计算指引步骤",
      guideLoadingHint: "等待神龛规则、库存或市场数据完成读取。",
      guideComplete: "当前计划已经完成",
      guideCompleteHint: "目标神龛均已达到规划等级。",
      guideMissingCredits: "下一步：补齐 {count} 种信用点",
      guideMissingCreditsHint: "请在公会商店选择：{items}",
      guideChooseItem: "下一步：选择 {item}",
      guideChooseItemHint: "这是当前 {credit} 的最优兑换物品。",
      guideSetQuantity: "下一步：输入 {count} 批",
      guideSetQuantityHint: "预计消耗 {items} 个{item}，获得 {credits} 点。",
      guideSetQuantityLimitHint: "总共还需 {remaining} 批；单次最多可填 {max} 批。",
      guideQuantityPlanSummary: "完成当前规划需要「{item}」{items}个，获得「{credit}」{credits}个",
      guideQuantityCurrentExchange: "本次填写 {count} 批",
      guideTokenQuantityDetail: "本次填写 {batches} 批，将使用 {items} 枚公会代币",
      guideUseGuildTokens: "下一步：使用 {count} 枚公会代币",
      guideUseGuildTokensHint: "当前已为 {credit} 选择公会代币兑换。",
      guideUnavailable: "暂时无法生成兑换指引",
      guideUnavailableHint: "当前信用点没有可用市场方案，请刷新市场数据或切换兑换方式。",
      guideBlocked: "仍有非信用点材料缺口",
      guideBlockedHint: "请先补齐：{items}",
      guideUpgradeShrine: "材料已齐，可以升级神龛",
      guideUpgradeShrineHint: "请前往升级：{shrines}",
      nativeGuildShopTab: "商店",
      waitingUpgradeRules: "等待神龛升级数据...",
      author: "作者：柆雨",
      support: "遇到问题或无法获取最新版，请加群：437320340",
      fallbackInstaller: "无法打开 Greasy Fork？使用备用分发安装",
      noMarketEstimate: "暂无可估算的市场价格",
      noMarketEstimateWithinPriceLimit: "没有单价不超过 {limit}M 的可用兑换物品；清空价格上限可显示全部",
      item: "物品",
      exchange: "兑换",
      perCredit: "每点",
      targetCost: "目标成本",
      tokenExchangeValue: "{token}兑换价值",
      noMarketValue: "暂无市场估算",
      noExchangeRules: "未读取到兑换规则。请刷新游戏页面后重新打开公会商店。",
      readingRules: "已读取 {count} 条兑换规则，正在读取公开市场快照...",
      snapshotLoadFailed: "市场快照读取失败：{message}",
      snapshotFallbackUsed: "无法获取新快照，当前显示约 {minutes} 分钟前保存的旧数据；为避免继续触发限制，已暂缓请求。",
      snapshotFallbackNotice: "新市场数据暂时不可用，当前使用已保存的旧价格。",
      credits: "信用点",
      goldPerCredit: "金币 / 信用",
      singleExchange: "单次兑换",
      marketCost: "市场成本",
      exchangeRecommendation: "兑换最优推荐",
      collapseExchangeAdvisor: "收起兑换推荐",
      expandExchangeAdvisor: "展开兑换推荐",
      advisorReferenceSelected: "卖出右一（税 {tax}%）·买入{reference}",
      advisorReference: "买入参考{reference}",
      chooseItem: "请选择兑换物品以计算卖出后替代方案。",
      alreadyOptimal: "当前选择已是最优物品，无需卖出再回购。",
      sellAndBuyMore: "卖出后改买可多获得 <strong>+{count}</strong> {credit}。",
      directMore: "直接兑换可多获得 <strong>{count}</strong> {credit}。",
      sameCredits: "两种方案可获得相同的信用点。",
      selected: "当前选择",
      selectedOptimal: "当前选择（最优）",
      bestItem: "最优物品",
      directExchange: "直接兑换",
      afterTax: "税后所得",
      buybackExchange: "回购兑换",
      purchaseCost: "买入成本",
      noSellPrice: "当前物品暂无公开收购价，无法估算卖出后回购。",
      noAffordableReplacement: "售出当前数量后税后可得 {gold}，不足以回购其他可兑换物品。",
      trialHistory: "历史试炼数据",
      analysisTitle: "试炼数据分析",
      analysisOverview: "单次试炼概览",
      analysisRanking: "成员贡献排行",
      analysisComparison: "同项目跨周对比",
      analysisMember: "成员历史表现",
      analysisCoverage: "成员记录分布",
      analysisScatter: "战斗贡献分布",
      analysisScope: "公会范围",
      analysisProject: "试炼项目",
      analysisWeek: "试炼周 / 记录",
      analysisMetric: "分析指标",
      analysisSearch: "搜索成员",
      analysisSearchPlaceholder: "输入成员名筛选排行、记录分布和散点",
      analysisRecordedMembers: "记录人数",
      analysisTotalMetric: "{metric}合计",
      analysisMean: "人均值",
      analysisMedian: "中位数",
      analysisKnown: "{count} 位成员中仅 {known} 位有该指标；合计、人均和中位数按已知值计算。",
      analysisShow: "显示范围",
      analysisTop10: "前 10 名",
      analysisAll: "全部成员",
      analysisTop5: "前 5 位成员贡献占比",
      analysisRankingHint: "占比分母为本次全部已知成员数值之和，搜索不会改变排名和占比。点击姓名查看历史。",
      analysisNoMembers: "没有匹配成员，请调整搜索内容。",
      analysisNoRatio: "无法计算占比 / 增幅",
      analysisNeedTwo: "至少需要两个不同试炼周的同项目记录，才能比较变化。",
      analysisMissing: "该指标暂无已知数值。",
      analysisFrom: "起始周",
      analysisCohort: "成员范围",
      analysisAllRecorded: "各周全部已记录成员",
      analysisShared: "所选各周都有记录的成员",
      analysisMeasure: "对比数值",
      analysisMeasure_count: "记录人数",
      analysisMeasure_total: "总量",
      analysisMeasure_mean: "人均值",
      analysisMeasure_median: "中位数",
      analysisCompareHint:
        "仅比较当前项目，截至所选记录所在周。人数、层数和参与时长可能不同，增长不等同于实力提升。缺少的周不补零。",
      analysisSharedCount: "共同成员 {count} 位。",
      analysisAmbiguousWeeks: "有 {count} 周存在多份同项目记录，已从对比中排除；当前周使用你选定的记录。",
      analysisChange: "相对起始周变化",
      analysisComparisonData: "各周数值明细",
      analysisOpenMember: "查看 {name} 的历史表现",
      analysisMatch_id: "角色 ID 匹配",
      analysisMatch_name: "同名匹配",
      analysisMatch_isolated: "身份不明确，仅此条记录",
      analysisMemberHint: "不同项目分别解释；下方变化只与此前同项目记录比较。没有记录不表示缺席。",
      analysisMemberTrend: "{trial} · {metric}历史",
      analysisMemberData: "成员逐次明细",
      analysisRecord: "日期与项目",
      analysisValues: "记录数值",
      analysisRankShare: "指标 / 名次 · 占比",
      analysisPrevious: "相对此前同项目",
      analysisCoverageHint: "按已保存记录展示，不是出勤率。战斗任一指标大于零记为有贡献；全部已知且为零才记为零。",
      analysisCell_positive: "有贡献",
      analysisCell_zero: "明确为零",
      analysisCell_unknown: "数值未知",
      analysisCell_absent: "无记录",
      analysisPrev: "上一页",
      analysisNext: "下一页",
      analysisMemberPages: "成员页",
      analysisRecordPages: "记录页",
      analysisCombatOnly: "选择战斗试炼后显示输出与治疗／抗伤分布。生活工作量不与战斗数值混算。",
      analysisYAxis: "纵轴指标",
      analysisScatterHint:
        "每个点代表一位成员；悬停或键盘聚焦查看数值，点击查看成员历史。重叠点可用 Tab 逐一查看，不根据位置判定职业或强弱。",
      analysisPointHint: "悬停或聚焦散点查看成员数值。",
      analysisMethod: "统计口径与数据限制",
      analysisMethodText:
        "只分析已保存的成员明细，原表占比不参与计算。零值与缺失值分开处理；总量为零时不计算占比，基期为零时不计算增幅。不同项目不合并评分。",
      analysisUnknownGuild:
        "当前为公会未注明的手动记录组；跨记录比较仅在这些数据来自同一公会时有意义，请勿混入其他公会数据。",
      analysisIdentityHint:
        "优先按角色 ID 关联；无 ID 时按完全相同的姓名匹配并标注。重名或前成员不跨记录合并，疑似拼写错误不自动修正。",
      trialImport: "导入 JSON",
      trialImportFile: "选择试炼历史 JSON 文件",
      trialImportHint:
        "支持历史导出文件和手动整理记录（最大 10 MB）。先预览再保存；可补全未知日期及周次，重复或统计冲突记录会跳过。",
      trialImportReading: "正在读取文件…",
      trialImportPreview: "导入预览",
      trialImportSummary: "新增 {added} 项 · 补全周次 {dated} 项 · 重复 {duplicates} 项 · 冲突 {conflicts} 项",
      trialImportStatus_new: "新增",
      trialImportStatus_dated: "补全日期与周次",
      trialImportStatus_duplicate: "重复，跳过",
      trialImportStatus_conflict: "内容不同，保留已有记录",
      trialImportMemberCount: "{count} 位成员",
      trialImportConfirm: "确认导入 {count} 项",
      trialImportCancel: "取消",
      trialImportTooLarge: "文件过大，请选择不超过 10 MB 的 JSON 文件。",
      trialImportInvalidJson: "文件不是有效 JSON，或包含不安全的字段。请检查文件内容。",
      trialImportInvalidFile: "格式不支持。请选择本插件导出的文件，或符合手动整理格式的文件（1–1,000 项记录）。",
      trialImportInvalidRecord: "第 {index} 项记录格式有误：请检查日期、成员、项目标识和非负统计数值；本次未导入。",
      trialImportDuplicateKey: "第 {index} 项记录与文件内另一项使用相同标识，请先删除重复项；本次未导入。",
      trialImportReadFailed: "无法读取文件，请重新选择。",
      trialImportComplete:
        "已导入 {added} 项，补全周次 {dated} 项，跳过 {duplicates} 项重复记录和 {conflicts} 项冲突记录。",
      trialImportSaveFailed: "保存失败，本次更改已撤回；请检查浏览器存储空间后重试。",
      trialImportPartial: "保存失败，本次仍保留新增 {added} 项、补全周次 {dated} 项。重试会跳过已保存项。",
      trialUnknownDate: "日期未注明",
      trialUnknownGuild: "公会未注明",
      trialManualSource: "手动整理",
      trialSourceMessageTime: "原始消息时间：{time}",
      trialAutomaticSource: "游戏采集",
      trialManualDescription: "手动整理 · {date} · 未提供的公会点数、层数与成员 ID 保持未知。",
      trialHistoryHint:
        "试炼结束后，打开游戏中的“统计”即可自动归档本次返回的全部已完成项目。记录保存在当前浏览器，按服务器和角色隔离；未采集的往期数据可通过手动整理文件导入。",
      trialHistoryEmpty: "暂无记录。可导入历史文件，或在试炼结束后打开游戏中的“统计”。",
      trialSavedCount: "已保存 {count} 项试炼记录。",
      trialSaveFailed: "部分记录尚未保存到浏览器。请先导出备份，再检查浏览器存储空间；当前页面仍保留待保存数据。",
      trialLoadFailed: "部分本地记录读取失败，已保留原数据。当前仅显示可读取的记录。",
      trialChoose: "选择历史试炼",
      trialExport: "导出全部 JSON",
      trialSkilling: "生活试炼",
      trialCombat: "战斗试炼",
      trialSummary: "{count} 位成员 · {points} 公会点数 · 最高第 {tier} 层",
      trialCaptured: "统计读取于 {time}",
      trialStatsTable: "成员试炼统计",
      trialMember: "成员",
      trialFormerMember: "名称未读取",
      trialRaw: "查看完整原始记录",
      trialField_workDone: "工作量",
      trialField_damageDealt: "造成伤害",
      trialField_healingDone: "治疗量",
      trialField_premitigatedDamageTaken: "减伤前承伤",
      trialName_milking: "挤奶",
      trialName_badger: "试炼獾",
      trialName_chameleon: "试炼变色龙",
      trialName_jellyfish: "试炼水母",
      trialName_hedgehog: "试炼刺猬",
      trialName_swarm: "试炼虫群",
      trialName_foraging: "采摘",
      trialName_woodcutting: "伐木",
      trialName_cheesesmithing: "奶酪锻造",
      trialName_crafting: "制作",
      trialName_tailoring: "缝纫",
      trialName_cooking: "烹饪",
      trialName_brewing: "冲泡",
      trialName_alchemy: "炼金",
      trialName_enhancing: "强化",
      sidebarCredit: "公会助手"
    },
    en: {
      unknownItem: "Unknown item",
      priceReferenceA: "Lowest ask",
      priceReferenceATitle: "Lowest ask: the current price to buy immediately",
      priceReferenceB: "Highest bid",
      priceReferenceBTitle: "Highest bid: quotes below the tradable range are ignored",
      marketItem: "View {item} in Marketplace",
      updateChecking: "Current v{current} · Latest: checking...",
      updateAvailable: "Current v{current} · Latest v{latest} · Update available",
      updateNow: "Update now",
      updateLatest: "Current v{current} · Latest v{latest} · Up to date",
      updateUnavailable: "Current v{current} · Latest: unavailable",
      shrineForce: "Force Shrine",
      shrineTempo: "Tempo Shrine",
      shrineSpirit: "Spirit Shrine",
      shrineRarity: "Rarity Shrine",
      shrineScholar: "Scholar Shrine",
      domainLife: "Life",
      domainCombat: "Combat",
      shrineWithDomain: "{shrine} ({domain})",
      guildTargetApplied: "Set {domain} plans to the current guild shrine levels; {count} upgrade(s) are needed.",
      guildTargetComplete:
        "All {domain} shrines already meet their guild building levels; no extra materials are needed.",
      plansCleared: "Cleared all shrine upgrade plans.",
      level: "Lv. {level}",
      targetButtonReady: "Set every matching shrine target to its current guild level",
      targetButtonMissing: "Guild shrine building levels are incomplete: {missing}",
      targetSummary: "{domain} {count}/{total}{missing}",
      targetSummaryMissing: " (unread: {missing})",
      shrineLevelsRead: "Guild shrine levels read: {summaries}.",
      shrineLevelsReading: "Reading current guild shrine building levels…",
      shrine: "Shrine",
      startLevel: "Starting level",
      targetLevel: "Target level",
      removePlan: "Remove this plan",
      gold: "gold",
      guildTokens: "guild tokens",
      noSnapshotEstimate: "The public market snapshot is unavailable, so the gold cost cannot be estimated.",
      partialEstimatedCost: "Estimated cost (priced items only)",
      estimatedTotalCost: "Estimated total cost",
      partialAfterInventory: "After-inventory gap (priced items only)",
      afterInventory: "Still needed after inventory",
      inventoryUnavailable: "Backpack inventory is unavailable; the gap assumes you own 0 items.",
      noCreditPrice: "No usable market price for: {items}.",
      costSummary: "Cost summary",
      inventoryAndMissing: "Owned {owned} · Missing {missing}",
      inventory: "Owned {count}",
      inventoryNotRead: "Inventory unavailable",
      inventoryCoveredNoExchange: "Existing inventory covers this requirement; no exchange is needed",
      backpackInventory: "Backpack: {count}",
      notRead: "unavailable",
      useGuildTokensForMissingCredits: "Use guild tokens for every credit",
      useGuildTokensForMissingCreditsHint: "Select or clear all, or switch each credit card individually below.",
      guildTokenCreditPlanActive: "Every missing credit is calculated as a guild-token exchange.",
      guildTokenCreditPlanPartialActive: "{count} credit type(s) use guild-token exchanges.",
      guildTokenCreditPlanSummary: "{count} guild tokens are allocated to credit exchanges.",
      autoGuildTokenBudget: "Automatic token budget",
      autoGuildTokenBudgetHint: "Allocates tokens from highest to lowest current market exchange value.",
      autoGuildTokenBudgetAvailable: "Up to {count} available",
      autoGuildTokenPlanSummary: "Automatically allocated {count} inventory guild tokens by exchange value.",
      autoGuildTokenExchangeNeeds: "Auto-allocated tokens",
      autoGuildTokenCoverage: "Covers {count} credits",
      optimalItemCreditMode: "Best item",
      guildTokenCreditMode: "Guild tokens",
      creditExchangeModeTitle: "Current mode: {mode}. Click to switch.",
      guildTokenExchangeNeeds: "Tokens needed",
      optimalExchangeNeeds: "Best exchange needs",
      exchangeRate: "{items} → {credits}",
      itemQuantity: "{count} {unit}",
      creditQuantity: "{count} {unit}",
      optimalExchangeUnavailable: "Best exchange: no usable market price",
      requiredThisTime: "Needed now",
      noGuildRules: "Shrine upgrade rules are unavailable. Refresh the game, then reopen the guild.",
      noUpgradePlans: "There are no shrine upgrade plans yet.",
      noUpgradePlansHint: "Select Add shrine, or use a batch-fill button above to create plans.",
      allBuffsMaxed: "All shrine buffs are already at their maximum level.",
      noUpgradeMaterials: "There are no shrine upgrade materials to calculate.",
      missingLevelCost: "Missing upgrade cost data for level {level}.",
      invalidLevels: "The starting or target level is invalid.",
      mergedUpgradePlans: "Combined material costs for {count} shrine upgrade plan(s).",
      unknownCurrentLevels:
        "Current shrine levels are unavailable, so plans start at level 0. Please verify or adjust the starting level.",
      snapshotFailed: "The public market snapshot failed to load, so the gold cost is not estimated yet.",
      panelTitle: "Guild Assistant",
      creditValue: "Credit value",
      creditValueHint:
        "Compare public market costs for the target amount; the first item is the current best exchange.",
      shrineUpgrade: "Shrine upgrades",
      guildConstruction: "Guild construction",
      panelViewOrder: "Tab order",
      moveViewLeft: "Move current tab left",
      moveViewRight: "Move current tab right",
      interfaceSettings: "Settings",
      interfaceSettingsHint:
        "Choose what batch fill includes and which plugin pages are visible. Changes apply locally.",
      openInterfaceSettings: "Open settings",
      closeInterfaceSettings: "Close settings",
      shrineAutofillRange: "Batch-fill scope",
      shrineAutofillRangeHint:
        "Clear an item to stop batch fill from adding or updating it. Existing plans are never deleted.",
      settingsShrinesLoading: "Reading configurable guild shrines…",
      settingsShrinesEmpty: "Game data is available, but there are no configurable guild shrines.",
      interfaceVisibility: "Interface",
      showConstructionView: "Show the Guild construction page",
      showConstructionViewHint: "Turning this off hides the tab but keeps every construction plan for later.",
      settingsSaved: "Settings saved.",
      settingsSaveFailed: "The change is active but could not be saved; it may reset after a page refresh.",
      constructionViewShown: "The Guild construction page is now visible.",
      constructionViewHidden: "The Guild construction page is hidden; its plans are still saved.",
      constructionReadOnly: "Admin planning tool · calculates only and never upgrades buildings",
      guildPointBudget: "Available guild points",
      manualBudget: "Manual budget",
      budgetOptional: "Leave blank to use the current points read from the game",
      invalidGuildPointBudget: "Enter a whole number of 0 or more.",
      guildPointTrend: "Weekly Guild Points",
      guildPointOverview: "Guild points & budget",
      guildPointStatisticsHeading: "Points & history",
      buildingCatalogCurrentLevel: "Current level {current}",
      buildingCatalogUnknownPlannedLevel: "Unread · Plan level {current} → {target}",
      buildingCatalogPlannedLevel: "Level {current} → {target} · In plan",
      buildingCatalogUnknownLevel: "Unread · Plan from level 0",
      guildPointPlanningHeading: "Construction budget",
      guildPointStartingBalance: "Custom starting points",
      guildPointFollowBalance: "Use game balance",
      guildPointStartingBalanceHint: "Optional. Clear to use the available game balance.",
      guildPointTrendHint: "Tracks lifetime Guild Point increases, so building spending does not affect the history.",
      guildPointAutoSaved: "Auto-saved",
      guildPointSavedSnapshot: "Saved snapshot",
      currentAvailableGuildPoints: "Available now",
      currentWeekGuildPoints: "This week's trial points",
      predictedCurrentWeekGuildPoints: "This week's forecast",
      latestWeeklyGuildPoints: "Latest complete week",
      weeklyGuildPointGrowth: "Week-over-week",
      guildPointEstimatedGrowth: "Estimated weekly growth",
      nextWeekGuildPointForecast: "Next-week forecast",
      guildPointHistoryUnavailable:
        "Guild Points are not available yet. Open the Guild page to create a local baseline.",
      guildPointHistoryBaseline:
        "The lifetime-point baseline is saved. The next weekly reward will create the first record.",
      guildPointForecastNeedsHistory:
        "Weekly records are being saved. Two consecutive weeks are required for a forecast.",
      guildPointForecastColdStart:
        "The prior {count} weeks averaged {average} points, and this week has earned {current}. A midpoint trend fit estimates {growth} points of weekly growth and {forecast} next week. The result can change until this week ends.",
      guildPointForecastMethod: "Forecast from the average change over the latest {count} consecutive complete weeks.",
      guildPointForecastEstimatedMethod:
        "Forecast from the average change over the latest {count} complete weeks, including records filled from the lifetime total.",
      guildPointHistoryConflict:
        "Historical weekly points exceed the game's lifetime total, so forecasting is paused. Check manual entries or reset weekly records.",
      guildPointForecastWeeks: "Forecast lookback",
      guildPointForecastWeeksHint: "Uses only the latest consecutive complete weeks.",
      increaseGuildPointForecastWeeks: "Increase the forecast lookback by 1 week",
      decreaseGuildPointForecastWeeks: "Decrease the forecast lookback by 1 week",
      guildPointPlanningWeeks: "Planning horizon",
      guildPointPlanningOptions: "Forecast settings",
      guildPointPlanningWeeksHint:
        "0 uses current points only; values above 0 add forecast weekly output to the available budget.",
      increaseGuildPointPlanningWeeks: "Increase the planning horizon by 1 week",
      decreaseGuildPointPlanningWeeks: "Decrease the planning horizon by 1 week",
      guildPointPlanningCurrentOnly: "Current points only",
      guildPointWeekCount: "{count} weeks",
      guildPointWeekWithDate: "Week {count} ({date})",
      guildPointPlanningNeedsBalance: "Available Guild Points have not been read yet.",
      guildPointPlanningNeedsForecast:
        "The current-point budget is preserved; future weeks cannot be added because history is insufficient or conflicting.",
      guildPointPlanningBudgetCurrent: "Planning budget: {total} current points.",
      guildPointPlanningBudgetProjected: "Planning budget: {current} + {weeks} weeks × {weekly} = {total} points.",
      recentGuildPointHistory: "Recent weekly records",
      manualGuildPointWeek: "Week",
      manualGuildPointEarned: "Points earned that week",
      manualGuildPointEarnedForWeek: "Guild Points earned for {week}",
      guildPointHistorySource: "Source",
      saveManualGuildPointHistory: "Save full table",
      manualGuildPointHint:
        "Gray placeholders are estimates. Confirm the warning before editing tracked values. Clear and save to auto-fill an original tracked zero, or restore a nonzero original. Entering 0 keeps a zero value. The current week is read-only.",
      manualGuildPointHistoryEmpty: "There are no completed trial weeks to enter yet.",
      guildPointManualWeekOption: "Starting {week}",
      guildPointSourceTracked: "Game tracked",
      guildPointSourceTrackedEditing: "Correction not saved",
      guildPointSourceManual: "Manual",
      guildPointSourceManualOverride: "Manual override",
      guildPointSourceEstimated: "Auto-filled",
      guildPointSourceEmpty: "Not entered",
      guildPointSourceCurrent: "Tracking now",
      guildPointSourceCurrentEstimated: "Current-week forecast",
      guildPointSourceCurrentPending: "Not started this week",
      guildPointSourceCurrentUnavailable: "Not loaded",
      currentGuildPointWeek: "Current week",
      removeManualGuildPointWeek: "Remove the manual record for {week}",
      manualGuildPointWeekSaved: "Historical Guild Points were saved and missing weeks were recalculated.",
      manualGuildPointWeekTracked: "This week already has a game-tracked record and cannot be overwritten manually.",
      editTrackedGuildPointWeek: "Edit the game-tracked value for {week}",
      editTrackedGuildPointWeekShort: "Edit",
      trackedGuildPointEditWarningTitle: "Override the game-tracked value?",
      trackedGuildPointEditWarningBody:
        "The {points} points for {week} came from game tracking. Continuing lets you enter a manual correction. It affects only this plugin's history, forecast, and construction estimate; it does not change game data.",
      trackedGuildPointEditWarningHint:
        "Clear and save to auto-fill an original tracked zero, or restore a nonzero original.",
      cancelTrackedGuildPointEdit: "Cancel",
      confirmTrackedGuildPointEdit: "Continue editing",
      manualGuildPointWeekInvalid: "Choose a completed trial week and enter a non-negative integer.",
      manualGuildPointWeekRemoved: "The manual record was removed and the missing week is auto-filled again.",
      manualGuildPointHistorySaved: "The historical Guild Point table was saved; blank weeks will remain estimated.",
      constructionEta: "Construction ETA",
      constructionEtaNoPlan: "No plan yet",
      constructionEtaNoPlanHint: "Add a building to estimate completion time.",
      constructionEtaNeedsBalance: "Available Guild Points are unavailable; enter a manual budget.",
      constructionEtaNeedsForecast: "Two consecutive complete weeks are required for an ETA.",
      constructionEtaHistoryConflict: "Weekly history conflicts with the lifetime total, so the ETA is paused.",
      constructionEtaNoGrowth: "The weekly forecast is zero, so an ETA is unavailable.",
      constructionEtaCovered: "Covered by current points",
      constructionEtaCoveredHint: "The plan can be completed without waiting for more weekly points.",
      constructionEtaWeeks: "About {count} weeks",
      constructionEtaDetail: "About {points} points per week with {shortfall} still needed.",
      constructionEtaDetailEstimated:
        "Using the historical backfill estimate of about {points} points per week, with {shortfall} still needed.",
      exportGuildPointHistory: "Export weekly CSV",
      resetGuildPointHistory: "Reset weekly records",
      resetGuildPointHistoryConfirm:
        "Reset weekly Guild Point records for this character? Construction plans stay intact, but this cannot be undone.",
      guildPointHistoryReset:
        "Weekly records for this character were reset and a new baseline was created from the current lifetime total.",
      guildPointCsvWeekStart: "Week start",
      guildPointCsvEarned: "Guild Points earned",
      guildPointCsvStatus: "Record status",
      guildPointCsvComplete: "Complete week",
      guildPointCsvTracking: "Current week tracking",
      guildPointCsvManual: "Manual",
      guildPointCsvEstimated: "Auto-filled",
      guildPointCsvFileName: "milky-way-idle-guild-point-history.csv",
      plannedSpend: "Planned spend",
      plannedUpgrades: "Planned upgrades",
      affordableUpgrades: "Budget covers",
      remainingPoints: "Budget remaining",
      overBudgetBy: "Over budget",
      constructionPlanScale: "{buildings} buildings · {steps} levels",
      constructionBudgetEmptySummary: "Add a building to see what the budget can cover.",
      constructionNoBudgetSummary: "No budget set · {total} upgrades planned",
      constructionBudgetAllFit: "The budget covers all {total} upgrades.",
      constructionBudgetStopsBefore: "Covers {affordable}/{total}; {building} {from}→{to} needs {count} more",
      buildingCatalog: "Building catalog",
      buildingCatalogHint: "Choose buildings to add; the picker stays open for batch planning.",
      addBuilding: "Add building",
      closeBuildingPicker: "Close building catalog",
      buildingCategoryFilter: "Building categories",
      buildingCategoryAll: "All",
      buildingCategoryCore: "Core",
      buildingCategoryLife: "Life",
      buildingCategoryCombat: "Combat",
      buildingCategoryShrine: "Shrines",
      searchBuildings: "Search buildings",
      currentLevel: "Current level",
      buildingPlanCost: "Plan cost",
      buildingEditor: "Building plan editor",
      selectBuildingPrompt: "Select a building.",
      buildingMaxLevel: "Maximum level",
      notPlanned: "Not planned",
      buildingTileLabel: "{building}, current level {current}, target {target}",
      buildingTileAddLabel: "Add {building}, current level {current}",
      buildingTileDefaultZeroLabel: "Add {building}; level unavailable, planning from level 0",
      buildingTilePlannedLabel: "Go to {building} in the plan, target level {target}",
      buildingTileMaxLabel: "{building} is at maximum level and cannot be added",
      cancel: "Cancel",
      buildingAddedToPlan: "{building} added to the construction plan.",
      buildingRemovedFromPlan: "{building} removed from the construction plan.",
      buildingTargetUpdated: "{building}'s target is now level {target}.",
      buildingPlansReconciled: "Live levels adjusted {adjusted} plan(s) and removed {removed} completed plan(s).",
      addOneLevel: "Add 1 level",
      addFiveLevels: "Add 5 levels",
      removeBuildingPlan: "Remove from plan",
      movePlanUp: "Move {building} one position earlier",
      movePlanDown: "Move {building} one position later",
      constructionQueue: "Construction plan",
      constructionQueueHint: "Ordered by building; per-level costs are collapsed by default.",
      constructionQueueDragHint:
        "Drag the handles to reorder, use the earlier and later buttons, or press Alt with Up or Down.",
      dragConstructionPlan: "Reorder {building}",
      constructionQueueEmptyTitle: "Your construction plan is empty",
      constructionQueueEmpty: "Choose Add building to start planning.",
      constructionBudgetCutoff: "Budget cutoff · {count} remaining",
      constructionGroupBudgetCutoff: "Budget reaches level {level} · next level needs {count} more",
      constructionBudgetUnbudgeted: "No budget",
      constructionWithinBudget: "Within budget",
      constructionPartiallyWithinBudget: "Partially covered",
      constructionOverBudget: "Over budget",
      constructionSummary: "{buildings} building(s) · {steps} upgrade(s)",
      constructionPlanRowMeta: "Item {position} · {start}→{target} · {count} upgrade(s)",
      buildingTargetLabel: "Target level for {building}",
      increaseBuildingTarget: "Increase {building}'s target by {count} level(s)",
      expandBuildingSteps: "Expand per-level costs for {building}",
      collapseBuildingSteps: "Collapse per-level costs for {building}",
      removeBuildingFromPlan: "Remove {building} from the construction plan",
      buildingLevelsCoverage: "Levels loaded: {known}/{total}",
      buildingLevelsPartialHint: "{unknown} building level(s) are unavailable and default to level 0.",
      missingBuildingCost: "{building} is missing its level {level} cost and is excluded from the total.",
      moreConstructionActions: "More construction plan actions",
      clearBuildingPlans: "Clear construction plan",
      undoClearBuildingPlans: "Undo clear",
      copyBuildingPlan: "Copy plan",
      exportBuildingCsv: "Export CSV",
      buildingPlanCopied: "Construction plan copied.",
      buildingPlanCopyFailed: "Clipboard access failed. Use CSV export instead.",
      noBuildingMatches: "No buildings match these filters.",
      buildingPlanCleared: "Cleared {count} construction plan item(s).",
      buildingPlanRestored: "Restored {count} construction plan item(s).",
      buildingPlanReordered: "Construction order saved.",
      buildingPlanMovedToPosition: "{building} moved to item {position} of {total}.",
      constructionOrder: "Order",
      fromLevel: "From level",
      toLevel: "To level",
      stepCost: "Step cost",
      cumulativeCost: "Cumulative cost",
      buildingCsvFileName: "milky-way-idle-guild-construction-plan.csv",
      buildingGuildHall: "Guild Hall",
      buildingBuildersHall: "Builders' Hall",
      buildingArchives: "Archives",
      buildingTreasury: "Treasury",
      buildingSkillingEncampment: "Skilling Encampment",
      buildingWorkshop: "Guild Workshop",
      buildingForge: "Guild Forge",
      buildingLogShed: "Guild Log Shed",
      buildingGarden: "Guild Garden",
      buildingDairyBarn: "Guild Dairy Barn",
      buildingKitchen: "Guild Kitchen",
      buildingSewingParlor: "Guild Sewing Parlor",
      buildingBrewery: "Guild Brewery",
      buildingLibrary: "Guild Library",
      buildingLaboratory: "Guild Laboratory",
      buildingMysticalStudy: "Guild Mystical Study",
      buildingCombatEncampment: "Combat Encampment",
      buildingGym: "Guild Gym",
      buildingDojo: "Guild Dojo",
      buildingArcheryRange: "Guild Archery Range",
      buildingArmory: "Guild Armory",
      buildingDiningRoom: "Guild Dining Room",
      buildingObservatory: "Guild Observatory",
      targetCredits: "Target credits",
      increaseTargetCredits: "Increase target credits by 100",
      decreaseTargetCredits: "Decrease target credits by 100",
      marketReference: "Market price reference",
      priceReference: "Price reference",
      refreshEstimate: "Refresh market estimate",
      maxItemUnitPricePrefix: "Exclude items over",
      maxItemUnitPriceSuffix: "M",
      maxItemUnitPricePlaceholder: "No limit",
      maxItemUnitPriceInput: "Exclude conversion items priced over this many million gold",
      increaseMaxItemUnitPrice: "Increase the price limit by 10M",
      decreaseMaxItemUnitPrice: "Decrease the price limit by 10M",
      maxItemUnitPriceHint:
        "Filters by the selected left-one or right-one unit market price; clear the input to disable the filter",
      maxItemUnitPriceInvalid: "Enter an amount above 0M, such as 50",
      maxItemUnitPriceSaveFailed: "The price limit could not be saved; it remains active for this session",
      waitingExchangeRules: "Waiting for game exchange data...",
      guildShrineBatchPlan: "Batch plan by current guild shrine levels",
      setGuildLifeTarget: "Fill Life levels",
      setGuildCombatTarget: "Fill Combat levels",
      guildAutofillAllExcluded: "Every {domain} shrine is excluded from batch fill.",
      guildAutofillDomainExcluded: "No {domain} shrine participates in batch fill. Select one in Settings.",
      selectedUpgradePlanCount: "{count} upgrade plan(s) selected",
      addShrine: "Add shrine",
      clearAll: "Clear all",
      guideEnable: "Enable highlight guide",
      guideDisable: "Disable highlight guide",
      guideReady: "Highlight guide is ready",
      guideReadyHint: "It marks the next step from your plan and live inventory without taking actions.",
      guideNoPlans: "No shrine plan yet",
      guideNoPlansHint: "Add at least one shrine upgrade to start the guide.",
      guideLoading: "Calculating the next step",
      guideLoadingHint: "Waiting for shrine rules, inventory, or market data.",
      guideComplete: "The current plan is complete",
      guideCompleteHint: "Every target shrine has reached its planned level.",
      guideMissingCredits: "Next: fill {count} credit type(s)",
      guideMissingCreditsHint: "Choose in the Guild Shop: {items}",
      guideChooseItem: "Next: select {item}",
      guideChooseItemHint: "This is the current best exchange item for {credit}.",
      guideSetQuantity: "Next: enter {count} batches",
      guideSetQuantityHint: "Uses about {items} {item} and yields {credits} credits.",
      guideSetQuantityLimitHint: "{remaining} batches remain in total; this exchange allows up to {max}.",
      guideQuantityPlanSummary:
        "To complete the current plan, you need “{item}” × {items} and receive “{credit}” × {credits}.",
      guideQuantityCurrentExchange: "Enter {count} batches this time",
      guideTokenQuantityDetail: "Enter {batches} batches to use {items} guild tokens this time",
      guideUseGuildTokens: "Next: use {count} guild tokens",
      guideUseGuildTokensHint: "Guild-token exchange is selected for {credit}.",
      guideUnavailable: "An exchange step is unavailable",
      guideUnavailableHint:
        "No market option is available for this credit. Refresh prices or change its exchange mode.",
      guideBlocked: "Other materials are still missing",
      guideBlockedHint: "Fill these first: {items}",
      guideUpgradeShrine: "Materials are ready; upgrade the shrine",
      guideUpgradeShrineHint: "Upgrade: {shrines}",
      nativeGuildShopTab: "Shop",
      waitingUpgradeRules: "Waiting for shrine upgrade data...",
      author: "Author: 柆雨",
      support: "For help or updates, join QQ group: 437320340",
      fallbackInstaller: "Can't reach Greasy Fork? Use the fallback installer",
      noMarketEstimate: "No market price can be estimated yet",
      noMarketEstimateWithinPriceLimit:
        "No conversion item is available at or below {limit}M; clear the price limit to show all items",
      item: "Item",
      exchange: "Exchange",
      perCredit: "Per credit",
      targetCost: "Target cost",
      tokenExchangeValue: "{token} exchange value",
      noMarketValue: "No market estimate",
      noExchangeRules: "Exchange rules are unavailable. Refresh the game, then reopen the guild shop.",
      readingRules: "Read {count} exchange rule(s); loading the public market snapshot...",
      snapshotLoadFailed: "Market snapshot failed to load: {message}",
      snapshotFallbackUsed:
        "New market data is unavailable. Showing saved data from about {minutes} minute(s) ago; requests are paused to avoid further rate limits.",
      snapshotFallbackNotice: "New market data is unavailable; saved prices are being used.",
      credits: "credits",
      goldPerCredit: "gold / credit",
      singleExchange: "Direct exchange",
      marketCost: "Market cost",
      exchangeRecommendation: "Best exchange recommendation",
      collapseExchangeAdvisor: "Collapse exchange recommendation",
      expandExchangeAdvisor: "Expand exchange recommendation",
      advisorReferenceSelected: "Sell at highest bid ({tax}% tax) · Buy at {reference}",
      advisorReference: "Buy at {reference}",
      chooseItem: "Select an exchange item to compare sell-and-buy-back options.",
      alreadyOptimal: "The current item is already optimal; selling and buying back would not help.",
      sellAndBuyMore: "Selling and buying another item yields <strong>+{count}</strong> {credit}.",
      directMore: "Exchanging directly yields <strong>{count}</strong> more {credit}.",
      sameCredits: "Both options yield the same number of credits.",
      selected: "Current item",
      selectedOptimal: "Current item (best)",
      bestItem: "Best item",
      directExchange: "Direct exchange",
      afterTax: "After tax",
      buybackExchange: "Buy-back exchange",
      purchaseCost: "Purchase cost",
      noSellPrice: "This item has no public buy price, so sell-and-buy-back cannot be estimated.",
      noAffordableReplacement:
        "Selling this quantity yields {gold} after tax, which is not enough to buy an alternative exchange item.",
      trialHistory: "Trial history",
      analysisTitle: "Trial analytics",
      analysisOverview: "Trial overview",
      analysisRanking: "Member contributions",
      analysisComparison: "Compare the same trial across weeks",
      analysisMember: "Member history",
      analysisCoverage: "Member record coverage",
      analysisScatter: "Combat contribution distribution",
      analysisScope: "Guild scope",
      analysisProject: "Trial",
      analysisWeek: "Week / record",
      analysisMetric: "Metric",
      analysisSearch: "Find a member",
      analysisSearchPlaceholder: "Filter ranks, coverage and scatter by name",
      analysisRecordedMembers: "Recorded members",
      analysisTotalMetric: "Total {metric}",
      analysisMean: "Mean",
      analysisMedian: "Median",
      analysisKnown: "Only {known} of {count} members have this metric. Totals, mean and median use known values.",
      analysisShow: "Show",
      analysisTop10: "Top 10",
      analysisAll: "All members",
      analysisTop5: "Top 5 members' share",
      analysisRankingHint:
        "Shares use all known values in this trial. Search does not change ranks or shares. Select a name to see history.",
      analysisNoMembers: "No matching members. Adjust the search.",
      analysisNoRatio: "Ratio unavailable",
      analysisNeedTwo: "Comparison needs the same trial from at least two different weeks.",
      analysisMissing: "No known values for this metric.",
      analysisFrom: "Starting week",
      analysisCohort: "Member cohort",
      analysisAllRecorded: "All recorded members each week",
      analysisShared: "Members recorded in every selected week",
      analysisMeasure: "Compare",
      analysisMeasure_count: "Recorded members",
      analysisMeasure_total: "Total",
      analysisMeasure_mean: "Mean",
      analysisMeasure_median: "Median",
      analysisCompareHint:
        "Same trial only, through the selected week. Roster, tier and time may differ; growth is not a strength rating. Missing weeks are not zero.",
      analysisSharedCount: "{count} members in common.",
      analysisAmbiguousWeeks:
        "Excluded {count} ambiguous weeks with multiple records for this trial. The current week uses your selected record.",
      analysisChange: "Change from the starting week",
      analysisComparisonData: "Weekly values",
      analysisOpenMember: "View history for {name}",
      analysisMatch_id: "Matched by character ID",
      analysisMatch_name: "Matched by exact name",
      analysisMatch_isolated: "Unresolved identity; this record only",
      analysisMemberHint:
        "Interpret each trial separately. Changes compare earlier records of the same trial. No record does not mean absence.",
      analysisMemberTrend: "{trial} · {metric} history",
      analysisMemberData: "Member record details",
      analysisRecord: "Date and trial",
      analysisValues: "Recorded values",
      analysisRankShare: "Metric / rank · share",
      analysisPrevious: "Change from prior same trial",
      analysisCoverageHint:
        "Coverage of saved records, not attendance. Combat is positive when any metric is positive; zero requires all metrics to be known and zero.",
      analysisCell_positive: "Positive",
      analysisCell_zero: "Zero",
      analysisCell_unknown: "Unknown",
      analysisCell_absent: "No record",
      analysisPrev: "Previous",
      analysisNext: "Next",
      analysisMemberPages: "Member page",
      analysisRecordPages: "Record page",
      analysisCombatOnly:
        "Select a combat trial to see damage versus healing or damage taken. Skilling work is analyzed separately.",
      analysisYAxis: "Vertical axis",
      analysisScatterHint:
        "Each point is a member. Hover or focus for values; select for history. Use Tab to inspect overlapping points. Positions do not assign roles or strength.",
      analysisPointHint: "Hover or focus a point to inspect values.",
      analysisMethod: "Methods and data limits",
      analysisMethodText:
        "Calculations use saved member rows, not imported percentages. Missing values differ from zero. Zero totals have no shares; zero baselines have no percentage growth. Different trials are not scored together.",
      analysisUnknownGuild:
        "This group contains manual records without a guild. Cross-record comparisons are meaningful only if they belong to the same guild.",
      analysisIdentityHint:
        "Identity uses character IDs first; ID-less records match exact names and are labeled. Duplicate or former-member names stay separate. Suspected typos are not corrected.",
      trialImport: "Import JSON",
      trialImportFile: "Choose a trial history JSON file",
      trialImportHint:
        "Import exported history or manually transcribed records (up to 10 MB). Preview before saving. Missing dates and weeks can be filled in; duplicates and statistics conflicts are skipped.",
      trialImportReading: "Reading file…",
      trialImportPreview: "Import preview",
      trialImportSummary: "{added} new · {dated} dates filled · {duplicates} duplicates · {conflicts} conflicts",
      trialImportStatus_new: "New",
      trialImportStatus_dated: "Fill in date and week",
      trialImportStatus_duplicate: "Duplicate, skipped",
      trialImportStatus_conflict: "Different content; keep existing",
      trialImportMemberCount: "{count} members",
      trialImportConfirm: "Import {count} records",
      trialImportCancel: "Cancel",
      trialImportTooLarge: "Choose a JSON file no larger than 10 MB.",
      trialImportInvalidJson: "Invalid JSON or unsafe fields. Check the file contents.",
      trialImportInvalidFile:
        "Unsupported format. Choose an exported history or manual transcript file with 1–1,000 records.",
      trialImportInvalidRecord:
        "Record {index} is invalid. Check its date, members, trial identifier and non-negative numeric statistics. Nothing was imported.",
      trialImportDuplicateKey:
        "Record {index} repeats an identifier in this file. Remove the duplicate first. Nothing was imported.",
      trialImportReadFailed: "The file could not be read. Choose it again.",
      trialImportComplete:
        "Imported {added}; filled {dated} dates; skipped {duplicates} duplicates and {conflicts} conflicts.",
      trialImportSaveFailed:
        "Saving failed. Changes from this attempt were rolled back. Check browser storage space and retry.",
      trialImportPartial:
        "Saving failed; {added} new records and {dated} date updates remain saved. Retrying skips saved records.",
      trialUnknownDate: "Date unspecified",
      trialUnknownGuild: "Guild unspecified",
      trialManualSource: "Manual transcript",
      trialSourceMessageTime: "Original message time: {time}",
      trialAutomaticSource: "Game capture",
      trialManualDescription: "Manual transcript · {date} · Missing points, tiers and member IDs remain unknown.",
      trialHistoryHint:
        "After a trial ends, open the game’s Stats to archive every completed trial in its response. Records stay in this browser, separated by server and character. Past results can also be imported from manual transcripts.",
      trialHistoryEmpty: "No records yet. Import a history file or open the game’s Stats after a trial ends.",
      trialSavedCount: "{count} trial records saved.",
      trialSaveFailed:
        "Some records could not be saved. Export a backup before checking browser storage space; unsaved data is still available on this page.",
      trialLoadFailed:
        "Some local records could not be read. Their stored data was preserved; only readable records are shown.",
      trialChoose: "Choose a past trial",
      trialExport: "Export all JSON",
      trialSkilling: "Skilling trial",
      trialCombat: "Combat trial",
      trialSummary: "{count} members · {points} Guild Points · Highest tier {tier}",
      trialCaptured: "Stats captured at {time}",
      trialStatsTable: "Member trial statistics",
      trialMember: "Member",
      trialFormerMember: "Name unavailable",
      trialRaw: "View complete raw record",
      trialField_workDone: "Work done",
      trialField_damageDealt: "Damage dealt",
      trialField_healingDone: "Healing done",
      trialField_premitigatedDamageTaken: "Damage taken before mitigation",
      trialName_milking: "Milking",
      trialName_badger: "Trial Badger",
      trialName_chameleon: "Trial Chameleon",
      trialName_jellyfish: "Trial Jellyfish",
      trialName_hedgehog: "Trial Hedgehog",
      trialName_swarm: "Trial Swarm",
      trialName_foraging: "Foraging",
      trialName_woodcutting: "Woodcutting",
      trialName_cheesesmithing: "Cheesesmithing",
      trialName_crafting: "Crafting",
      trialName_tailoring: "Tailoring",
      trialName_cooking: "Cooking",
      trialName_brewing: "Brewing",
      trialName_alchemy: "Alchemy",
      trialName_enhancing: "Enhancing",
      sidebarCredit: "Guild Assistant"
    }
  };

  const ITEM_NAMES = {
    "zh-CN": {
      "/items/guild_token": "公会代币",
      "/items/green_guild_credit": "绿色公会信用点",
      "/items/brown_guild_credit": "棕色公会信用点",
      "/items/white_guild_credit": "白色公会信用点",
      "/items/blue_guild_credit": "蓝色公会信用点",
      "/items/purple_guild_credit": "紫色公会信用点",
      "/items/red_guild_credit": "红色公会信用点",
      "/items/silver_guild_credit": "银色公会信用点",
      "/items/gold_guild_credit": "金色公会信用点"
    },
    en: {
      "/items/guild_token": "Guild Token",
      "/items/green_guild_credit": "Green Guild Credit",
      "/items/brown_guild_credit": "Brown Guild Credit",
      "/items/white_guild_credit": "White Guild Credit",
      "/items/blue_guild_credit": "Blue Guild Credit",
      "/items/purple_guild_credit": "Purple Guild Credit",
      "/items/red_guild_credit": "Red Guild Credit",
      "/items/silver_guild_credit": "Silver Guild Credit",
      "/items/gold_guild_credit": "Gold Guild Credit"
    }
  };

  function supportedLocale(locale) {
    if (typeof locale !== "string") return null;
    const candidate = locale.trim().toLowerCase().replaceAll("_", "-");
    if (/^zh(?:-|$)/.test(candidate)) return "zh-CN";
    if (/^en(?:-|$)/.test(candidate)) return "en";
    return null;
  }

  function resolveLocaleCandidates(candidates, fallback = "zh-CN") {
    for (const candidate of Array.isArray(candidates) ? candidates : [candidates]) {
      const locale = supportedLocale(candidate);
      if (locale) return locale;
    }
    return supportedLocale(fallback) || "zh-CN";
  }

  function normalizeLocale(locale) {
    return supportedLocale(locale) || "en";
  }

  function interpolate(template, values) {
    return String(template).replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key) =>
      values && values[key] !== undefined ? String(values[key]) : `{${key}}`
    );
  }

  function createLocalizer(locale) {
    const normalizedLocale = normalizeLocale(locale);
    const strings = STRINGS[normalizedLocale];
    function t(key, values) {
      return interpolate(strings[key] || STRINGS.en[key] || key, values);
    }
    function number(value, digits) {
      if (value === null || value === undefined || !Number.isFinite(value)) return "-";
      return new Intl.NumberFormat(normalizedLocale, {
        maximumFractionDigits: digits === undefined ? 0 : digits
      }).format(value);
    }
    function quantity(key, count) {
      const formatted = number(count);
      if (normalizedLocale === "zh-CN") return t(key, { count: formatted });
      const unit =
        key === "creditQuantity"
          ? Number(count) === 1
            ? "credit"
            : "credits"
          : Number(count) === 1
            ? "item"
            : "items";
      return t(key, { count: formatted, unit });
    }
    function itemName(itemHrid) {
      return ITEM_NAMES[normalizedLocale][itemHrid] || "";
    }
    return { locale: normalizedLocale, t, number, quantity, itemName };
  }

  return { STRINGS, ITEM_NAMES, supportedLocale, resolveLocaleCandidates, normalizeLocale, createLocalizer };
});
