(function (root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.MwiGuildCreditLocalization = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const STRINGS = {
    "zh-CN": {
      unknownItem: "未知物品",
      priceReferenceA: "左一",
      priceReferenceATitle: "左一：最低出售价，可立即买入",
      priceReferenceB: "右一",
      priceReferenceBTitle: "右一：最高收购价，仅作理论参考",
      marketItem: "在市场中查看{item}",
      updateChecking: "当前版本 v{current} · 最新版本：检查中...",
      updateAvailable: "当前版本 v{current} · 最新版本 v{latest} · 发现新版本",
      updateNow: "立即更新",
      updateLatest: "当前版本 v{current} · 最新版本 v{latest} · 已是最新",
      updateUnavailable: "当前版本 v{current} · 最新版本：暂时无法读取",
      shrineForce: "力量神龛",
      shrineTempo: "节奏神龛",
      shrineSpirit: "精神神龛",
      shrineRarity: "稀有神龛",
      shrineScholar: "学者神龛",
      domainLife: "生活",
      domainCombat: "战斗",
      shrineWithDomain: "{shrine}（{domain}）",
      guildTargetApplied: "已按当前公会神龛等级设定{domain}计划，共 {count} 项需要升级。",
      guildTargetComplete: "当前已达到最大等级（{domain}）。",
      plansCleared: "已清空全部神龛升级计划。",
      level: "{level} 级",
      targetButtonReady: "按每座对应公会神龛的当前等级批量设定目标",
      targetButtonMissing: "尚未读取完整的公会神龛建筑等级：{missing}",
      targetSummary: "{domain} {count}/{total}{missing}",
      targetSummaryMissing: "（未识别：{missing}）",
      shrineLevelsRead: "公会神龛等级已读取：{summaries}。",
      shrineLevelsReading: "正在读取当前公会神龛建筑等级…",
      shrine: "神龛",
      startLevel: "起始等级",
      targetLevel: "目标等级",
      removePlan: "移除此项",
      gold: "金币",
      guildTokens: "公会代币",
      noSnapshotEstimate: "未读取到公开市场快照，暂无法估算金币成本。",
      partialEstimatedCost: "预计成本（已定价部分）",
      estimatedTotalCost: "预计总成本",
      partialAfterInventory: "库存后缺口（已定价部分）",
      afterInventory: "库存后仍需",
      inventoryUnavailable: "未读取背包库存，缺口暂按 0 件库存计算。",
      noCreditPrice: "以下信用点暂无可用市场价格：{items}。",
      costSummary: "成本概览",
      inventoryAndMissing: "库存 {owned} · 缺 {missing}",
      inventory: "库存 {count}",
      inventoryNotRead: "库存未读取",
      inventoryCoveredNoExchange: "现有库存已覆盖，无需兑换",
      backpackInventory: "背包库存 {count}",
      notRead: "未读取",
      useGuildTokensForMissingCredits: "全部信用点使用公会代币",
      useGuildTokensForMissingCreditsHint: "快速选择或清除全部；也可在每张信用点卡片单独切换。",
      guildTokenCreditPlanActive: "缺少的信用点已全部按公会代币兑换计算。",
      guildTokenCreditPlanPartialActive: "已选择 {count} 种信用点按公会代币兑换计算。",
      guildTokenCreditPlanSummary: "其中 {count} 公会代币用于兑换信用点。",
      autoGuildTokenBudget: "自动兑换代币预算",
      autoGuildTokenBudgetHint: "按每枚公会代币的市场兑换价值从高到低分配。",
      autoGuildTokenBudgetAvailable: "本次最多可用 {count}",
      autoGuildTokenPlanSummary: "已按兑换价值自动分配 {count} 枚库存公会代币。",
      autoGuildTokenExchangeNeeds: "自动分配代币",
      autoGuildTokenCoverage: "覆盖 {count} 信用点",
      optimalItemCreditMode: "最优物品",
      guildTokenCreditMode: "公会代币",
      creditExchangeModeTitle: "当前使用{mode}兑换；点击切换。",
      guildTokenExchangeNeeds: "代币兑换需",
      optimalExchangeNeeds: "最优兑换需",
      exchangeRate: "{items} → {credits}",
      itemQuantity: "{count} 个",
      creditQuantity: "{count} 点",
      optimalExchangeUnavailable: "最优兑换：暂无可用市场价格",
      requiredThisTime: "本次所需",
      noGuildRules: "未读取到神龛升级规则。请刷新游戏页面后重新打开公会。",
      allBuffsMaxed: "当前所有神龛增益均已满级。",
      noUpgradeMaterials: "当前没有需要计算的神龛升级材料。",
      missingLevelCost: "缺少 {level} 级升级成本数据。",
      invalidLevels: "起始等级或目标等级无效。",
      mergedUpgradePlans: "已合并 {count} 项神龛升级的材料成本。",
      unknownCurrentLevels: "未读取当前神龛等级，已按 0 级开始；请确认或手动调整“起始等级”。",
      snapshotFailed: "公开市场快照读取失败，暂未估算金币成本。",
      panelTitle: "公会助手",
      creditValue: "信用点性价比",
      creditValueHint: "按目标数量比较公开市场成本，首项为当前最优兑换。",
      shrineUpgrade: "神龛升级",
      guildConstruction: "公会建设",
      panelViewOrder: "页签顺序",
      moveViewLeft: "将当前页签左移",
      moveViewRight: "将当前页签右移",
      interfaceSettings: "设置",
      interfaceSettingsHint: "调整一键填充范围和插件页面；修改会立即在本机生效。",
      openInterfaceSettings: "打开设置",
      closeInterfaceSettings: "关闭设置",
      shrineAutofillRange: "一键填充范围",
      shrineAutofillRangeHint: "取消勾选后，一键填充不会新增或更新该神龛；已有计划不会删除。",
      settingsShrinesLoading: "正在读取可配置的公会神龛…",
      settingsShrinesEmpty: "已读取游戏数据，但没有可配置的公会神龛。",
      interfaceVisibility: "界面",
      showConstructionView: "显示公会建设页面",
      showConstructionViewHint: "关闭后隐藏页签；施工计划仍会保留，可随时重新开启。",
      settingsSaved: "设置已保存。",
      settingsSaveFailed: "设置已生效，但未能保存；刷新页面后可能恢复。",
      constructionViewShown: "已显示公会建设页面。",
      constructionViewHidden: "已隐藏公会建设页面；施工计划仍已保留。",
      constructionReadOnly: "管理员规划工具 · 只计算，不会执行建筑升级",
      guildPointBudget: "可用公会点数",
      manualBudget: "手工预算",
      budgetOptional: "留空则只计算总成本",
      invalidGuildPointBudget: "请输入不小于 0 的整数。",
      plannedSpend: "计划消耗",
      plannedUpgrades: "计划升级",
      affordableUpgrades: "预算可完成",
      remainingPoints: "预算剩余",
      overBudgetBy: "超出预算",
      constructionPlanScale: "{buildings} 座 · {steps} 级",
      constructionBudgetEmptySummary: "添加建筑后显示预算可执行范围。",
      constructionNoBudgetSummary: "未设置预算 · 共 {total} 次升级",
      constructionBudgetAllFit: "预算覆盖全部 {total} 次升级。",
      constructionBudgetStopsBefore: "可完成 {affordable}/{total} 次；下一项 {building} {from}→{to} 还差 {count}",
      buildingCatalog: "建筑目录",
      buildingCatalogHint: "选择建筑加入计划；可连续添加多座。",
      addBuilding: "添加建筑",
      closeBuildingPicker: "收起建筑目录",
      buildingCategoryFilter: "建筑分类",
      buildingCategoryAll: "全部",
      buildingCategoryCore: "基础",
      buildingCategoryLife: "生活",
      buildingCategoryCombat: "战斗",
      buildingCategoryShrine: "神龛",
      searchBuildings: "搜索建筑",
      currentLevel: "当前等级",
      buildingPlanCost: "计划成本",
      buildingEditor: "建筑计划编辑器",
      selectBuildingPrompt: "请选择一座建筑。",
      buildingMaxLevel: "已满级",
      notPlanned: "未计划",
      buildingTileLabel: "{building}，当前 {current} 级，目标 {target}",
      buildingTileAddLabel: "添加 {building}，当前 {current} 级",
      buildingTileUnknownLabel: "添加 {building}；当前等级未知，需先填写",
      buildingTilePlannedLabel: "定位到 {building} 的施工行，目标 {target} 级",
      buildingTileMaxLabel: "{building} 已满级，不能加入计划",
      currentBuildingLevelRequired: "当前等级尚未读取，请先填写后再加入计划。",
      currentBuildingLevelLabel: "{building} 当前等级",
      currentBuildingLevelHelp: "请输入 0–{max} 的整数。",
      currentBuildingLevelRange: "当前等级必须是 0–{max} 的整数。",
      addBuildingToPlan: "加入施工计划",
      cancel: "取消",
      buildingAddedToPlan: "已将 {building} 加入施工计划。",
      buildingRemovedFromPlan: "已将 {building} 移出施工计划。",
      buildingTargetUpdated: "{building} 的目标已更新为 {target} 级。",
      buildingPlansReconciled: "已按实时等级调整 {adjusted} 项计划，并移除 {removed} 项已完成计划。",
      addOneLevel: "加 1 级",
      addFiveLevels: "加 5 级",
      removeBuildingPlan: "移出计划",
      movePlanUp: "将 {building} 提前一位",
      movePlanDown: "将 {building} 延后一位",
      constructionQueue: "施工计划",
      constructionQueueHint: "按建筑分组排序；逐级费用默认收起。",
      constructionQueueDragHint: "拖动手柄排序，也可使用提前、延后按钮；键盘可按 Alt 加上下方向键。",
      dragConstructionPlan: "调整 {building} 的施工顺序",
      constructionQueueEmptyTitle: "施工计划为空",
      constructionQueueEmpty: "选择“添加建筑”开始规划。",
      constructionBudgetCutoff: "预算截止线 · 剩余 {count}",
      constructionGroupBudgetCutoff: "预算可升至 {level} 级 · 下一等级还差 {count}",
      constructionBudgetUnbudgeted: "待预算",
      constructionWithinBudget: "预算内",
      constructionPartiallyWithinBudget: "部分预算内",
      constructionOverBudget: "超预算",
      constructionSummary: "{buildings} 座建筑 · {steps} 次升级",
      constructionPlanRowMeta: "第 {position} 项 · {start}→{target} · {count} 次升级",
      buildingTargetLabel: "{building} 的目标等级",
      increaseBuildingTarget: "将 {building} 的目标提高 {count} 级",
      expandBuildingSteps: "展开 {building} 的逐级费用",
      collapseBuildingSteps: "收起 {building} 的逐级费用",
      removeBuildingFromPlan: "将 {building} 移出施工计划",
      buildingLevelsRead: "已读取当前公会建筑等级。",
      buildingLevelsUnknown: "未读取到当前公会建筑等级；请核对各建筑的起始等级。",
      buildingLevelsReadCompact: "等级已读取",
      buildingLevelsUnknownCompact: "等级暂不可用",
      buildingLevelsCoverage: "已读取 {known}/{total}",
      buildingLevelsPartialHint: "{unknown} 座建筑等级未知；添加前需填写当前等级。",
      missingBuildingCost: "{building} 缺少 {level} 级费用，未计入总成本。",
      moreConstructionActions: "更多施工计划操作",
      clearBuildingPlans: "清空施工计划",
      undoClearBuildingPlans: "撤销清空",
      copyBuildingPlan: "复制规划",
      exportBuildingCsv: "导出 CSV",
      buildingPlanCopied: "施工规划已复制。",
      buildingPlanCopyFailed: "无法写入剪贴板，请使用 CSV 导出。",
      noBuildingMatches: "没有符合筛选条件的建筑。",
      buildingPlanCleared: "已清空 {count} 项施工计划。",
      buildingPlanRestored: "已恢复 {count} 项施工计划。",
      buildingPlanReordered: "施工顺序已保存。",
      buildingPlanMovedToPosition: "{building} 已移至第 {position} 项，共 {total} 项。",
      constructionOrder: "顺序",
      fromLevel: "起始等级",
      toLevel: "目标等级",
      stepCost: "本级成本",
      cumulativeCost: "累计成本",
      buildingCsvFileName: "银河奶牛_公会建筑规划.csv",
      buildingGuildHall: "公会大厅",
      buildingBuildersHall: "建造者殿堂",
      buildingArchives: "档案馆",
      buildingTreasury: "金库",
      buildingSkillingEncampment: "生活营地",
      buildingWorkshop: "公会工作间",
      buildingForge: "公会锻造台",
      buildingLogShed: "公会木棚",
      buildingGarden: "公会花园",
      buildingDairyBarn: "公会奶牛棚",
      buildingKitchen: "公会厨房",
      buildingSewingParlor: "公会缝纫室",
      buildingBrewery: "公会冲泡坊",
      buildingLibrary: "公会图书馆",
      buildingLaboratory: "公会实验室",
      buildingMysticalStudy: "公会神秘研究室",
      buildingCombatEncampment: "战斗营地",
      buildingGym: "公会健身房",
      buildingDojo: "公会道场",
      buildingArcheryRange: "公会射箭场",
      buildingArmory: "公会军械库",
      buildingDiningRoom: "公会餐厅",
      buildingObservatory: "公会天文台",
      targetCredits: "目标信用点",
      marketReference: "市场价格参考",
      priceReference: "价格参考",
      refreshEstimate: "刷新市场估算",
      waitingExchangeRules: "等待游戏兑换数据...",
      guildShrineBatchPlan: "按当前公会神龛等级批量规划",
      setGuildLifeTarget: "填充生活等级",
      setGuildCombatTarget: "填充战斗等级",
      guildAutofillAllExcluded: "所有{domain}神龛均已从一键填充中排除。",
      guildAutofillDomainExcluded: "当前没有参与一键填充的{domain}神龛；请在设置中至少勾选一项。",
      selectedUpgradePlanCount: "已选择 {count} 项升级计划",
      addShrine: "添加神龛",
      clearAll: "清空全部",
      guideEnable: "开启高亮指引",
      guideDisable: "关闭高亮指引",
      guideReady: "高亮指引已待命",
      guideReadyHint: "开启后会根据规划和实时库存标出下一步，不会自动操作。",
      guideNoPlans: "尚未添加神龛计划",
      guideNoPlansHint: "添加至少一项神龛升级后即可开始指引。",
      guideLoading: "正在计算指引步骤",
      guideLoadingHint: "等待神龛规则、库存或市场数据完成读取。",
      guideComplete: "当前计划已经完成",
      guideCompleteHint: "目标神龛均已达到规划等级。",
      guideMissingCredits: "下一步：补齐 {count} 种信用点",
      guideMissingCreditsHint: "请在公会商店选择：{items}",
      guideChooseItem: "下一步：选择 {item}",
      guideChooseItemHint: "这是当前 {credit} 的最优兑换物品。",
      guideSetQuantity: "下一步：输入 {count} 批",
      guideSetQuantityHint: "预计消耗 {items} 个{item}，获得 {credits} 点。",
      guideSetQuantityLimitHint: "总共还需 {remaining} 批；单次最多可填 {max} 批。",
      guideQuantityLabel: "完成当前规划还需",
      guideQuantityUnit: "批",
      guideQuantityRemaining: "完成当前规划还需 {count} 批",
      guideQuantityCurrentExchange: "本次填写 {count} 批",
      guideTokenQuantityDetail: "本次填写 {batches} 批，将使用 {items} 枚公会代币",
      guideUseGuildTokens: "下一步：使用 {count} 枚公会代币",
      guideUseGuildTokensHint: "当前已为 {credit} 选择公会代币兑换。",
      guideUnavailable: "暂时无法生成兑换指引",
      guideUnavailableHint: "当前信用点没有可用市场方案，请刷新市场数据或切换兑换方式。",
      guideBlocked: "仍有非信用点材料缺口",
      guideBlockedHint: "请先补齐：{items}",
      guideUpgradeShrine: "材料已齐，可以升级神龛",
      guideUpgradeShrineHint: "请前往升级：{shrines}",
      nativeGuildShopTab: "商店",
      waitingUpgradeRules: "等待神龛升级数据...",
      author: "作者：柆雨",
      support: "遇到问题或无法获取最新版，请加群：437320340",
      fallbackInstaller: "无法打开 Greasy Fork？使用备用分发安装",
      noMarketEstimate: "暂无可估算的市场价格",
      item: "物品",
      exchange: "兑换",
      perCredit: "每点",
      targetCost: "目标成本",
      tokenExchangeValue: "{token}兑换价值",
      noMarketValue: "暂无市场估算",
      noExchangeRules: "未读取到兑换规则。请刷新游戏页面后重新打开公会商店。",
      readingRules: "已读取 {count} 条兑换规则，正在读取公开市场快照...",
      snapshotLoadFailed: "市场快照读取失败：{message}",
      credits: "信用点",
      goldPerCredit: "金币 / 信用",
      singleExchange: "单次兑换",
      marketCost: "市场成本",
      exchangeRecommendation: "兑换最优推荐",
      advisorReferenceSelected: "卖出右一（税 2%）·买入{reference}",
      advisorReference: "买入参考{reference}",
      chooseItem: "请选择兑换物品以计算卖出后替代方案。",
      alreadyOptimal: "当前选择已是最优物品，无需卖出再回购。",
      sellAndBuyMore: "卖出后改买可多获得 <strong>+{count}</strong> {credit}。",
      directMore: "直接兑换可多获得 <strong>{count}</strong> {credit}。",
      sameCredits: "两种方案可获得相同的信用点。",
      selected: "当前选择",
      selectedOptimal: "当前选择（最优）",
      bestItem: "最优物品",
      directExchange: "直接兑换",
      afterTax: "税后所得",
      buybackExchange: "回购兑换",
      purchaseCost: "买入成本",
      noSellPrice: "当前物品暂无公开收购价，无法估算卖出后回购。",
      noAffordableReplacement: "售出当前数量后税后可得 {gold}，不足以回购其他可兑换物品。",
      sidebarCredit: "信用"
    },
    en: {
      unknownItem: "Unknown item",
      priceReferenceA: "Lowest ask",
      priceReferenceATitle: "Lowest ask: the current price to buy immediately",
      priceReferenceB: "Highest bid",
      priceReferenceBTitle: "Highest bid: a theoretical reference only",
      marketItem: "View {item} in Marketplace",
      updateChecking: "Current v{current} · Latest: checking...",
      updateAvailable: "Current v{current} · Latest v{latest} · Update available",
      updateNow: "Update now",
      updateLatest: "Current v{current} · Latest v{latest} · Up to date",
      updateUnavailable: "Current v{current} · Latest: unavailable",
      shrineForce: "Force Shrine",
      shrineTempo: "Tempo Shrine",
      shrineSpirit: "Spirit Shrine",
      shrineRarity: "Rarity Shrine",
      shrineScholar: "Scholar Shrine",
      domainLife: "Life",
      domainCombat: "Combat",
      shrineWithDomain: "{shrine} ({domain})",
      guildTargetApplied: "Set {domain} plans to the current guild shrine levels; {count} upgrade(s) are needed.",
      guildTargetComplete:
        "All {domain} shrines already meet their guild building levels; no extra materials are needed.",
      plansCleared: "Cleared all shrine upgrade plans.",
      level: "Lv. {level}",
      targetButtonReady: "Set every matching shrine target to its current guild level",
      targetButtonMissing: "Guild shrine building levels are incomplete: {missing}",
      targetSummary: "{domain} {count}/{total}{missing}",
      targetSummaryMissing: " (unread: {missing})",
      shrineLevelsRead: "Guild shrine levels read: {summaries}.",
      shrineLevelsReading: "Reading current guild shrine building levels…",
      shrine: "Shrine",
      startLevel: "Starting level",
      targetLevel: "Target level",
      removePlan: "Remove this plan",
      gold: "gold",
      guildTokens: "guild tokens",
      noSnapshotEstimate: "The public market snapshot is unavailable, so the gold cost cannot be estimated.",
      partialEstimatedCost: "Estimated cost (priced items only)",
      estimatedTotalCost: "Estimated total cost",
      partialAfterInventory: "After-inventory gap (priced items only)",
      afterInventory: "Still needed after inventory",
      inventoryUnavailable: "Backpack inventory is unavailable; the gap assumes you own 0 items.",
      noCreditPrice: "No usable market price for: {items}.",
      costSummary: "Cost summary",
      inventoryAndMissing: "Owned {owned} · Missing {missing}",
      inventory: "Owned {count}",
      inventoryNotRead: "Inventory unavailable",
      inventoryCoveredNoExchange: "Existing inventory covers this requirement; no exchange is needed",
      backpackInventory: "Backpack: {count}",
      notRead: "unavailable",
      useGuildTokensForMissingCredits: "Use guild tokens for every credit",
      useGuildTokensForMissingCreditsHint: "Select or clear all, or switch each credit card individually below.",
      guildTokenCreditPlanActive: "Every missing credit is calculated as a guild-token exchange.",
      guildTokenCreditPlanPartialActive: "{count} credit type(s) use guild-token exchanges.",
      guildTokenCreditPlanSummary: "{count} guild tokens are allocated to credit exchanges.",
      autoGuildTokenBudget: "Automatic token budget",
      autoGuildTokenBudgetHint: "Allocates tokens from highest to lowest current market exchange value.",
      autoGuildTokenBudgetAvailable: "Up to {count} available",
      autoGuildTokenPlanSummary: "Automatically allocated {count} inventory guild tokens by exchange value.",
      autoGuildTokenExchangeNeeds: "Auto-allocated tokens",
      autoGuildTokenCoverage: "Covers {count} credits",
      optimalItemCreditMode: "Best item",
      guildTokenCreditMode: "Guild tokens",
      creditExchangeModeTitle: "Current mode: {mode}. Click to switch.",
      guildTokenExchangeNeeds: "Tokens needed",
      optimalExchangeNeeds: "Best exchange needs",
      exchangeRate: "{items} → {credits}",
      itemQuantity: "{count} {unit}",
      creditQuantity: "{count} {unit}",
      optimalExchangeUnavailable: "Best exchange: no usable market price",
      requiredThisTime: "Needed now",
      noGuildRules: "Shrine upgrade rules are unavailable. Refresh the game, then reopen the guild.",
      allBuffsMaxed: "All shrine buffs are already at their maximum level.",
      noUpgradeMaterials: "There are no shrine upgrade materials to calculate.",
      missingLevelCost: "Missing upgrade cost data for level {level}.",
      invalidLevels: "The starting or target level is invalid.",
      mergedUpgradePlans: "Combined material costs for {count} shrine upgrade plan(s).",
      unknownCurrentLevels:
        "Current shrine levels are unavailable, so plans start at level 0. Please verify or adjust the starting level.",
      snapshotFailed: "The public market snapshot failed to load, so the gold cost is not estimated yet.",
      panelTitle: "Guild Assistant",
      creditValue: "Credit value",
      creditValueHint:
        "Compare public market costs for the target amount; the first item is the current best exchange.",
      shrineUpgrade: "Shrine upgrades",
      guildConstruction: "Guild construction",
      panelViewOrder: "Tab order",
      moveViewLeft: "Move current tab left",
      moveViewRight: "Move current tab right",
      interfaceSettings: "Settings",
      interfaceSettingsHint:
        "Choose what batch fill includes and which plugin pages are visible. Changes apply locally.",
      openInterfaceSettings: "Open settings",
      closeInterfaceSettings: "Close settings",
      shrineAutofillRange: "Batch-fill scope",
      shrineAutofillRangeHint:
        "Clear an item to stop batch fill from adding or updating it. Existing plans are never deleted.",
      settingsShrinesLoading: "Reading configurable guild shrines…",
      settingsShrinesEmpty: "Game data is available, but there are no configurable guild shrines.",
      interfaceVisibility: "Interface",
      showConstructionView: "Show the Guild construction page",
      showConstructionViewHint: "Turning this off hides the tab but keeps every construction plan for later.",
      settingsSaved: "Settings saved.",
      settingsSaveFailed: "The change is active but could not be saved; it may reset after a page refresh.",
      constructionViewShown: "The Guild construction page is now visible.",
      constructionViewHidden: "The Guild construction page is hidden; its plans are still saved.",
      constructionReadOnly: "Admin planning tool · calculates only and never upgrades buildings",
      guildPointBudget: "Available guild points",
      manualBudget: "Manual budget",
      budgetOptional: "Leave blank to calculate cost without a budget",
      invalidGuildPointBudget: "Enter a whole number of 0 or more.",
      plannedSpend: "Planned spend",
      plannedUpgrades: "Planned upgrades",
      affordableUpgrades: "Budget covers",
      remainingPoints: "Budget remaining",
      overBudgetBy: "Over budget",
      constructionPlanScale: "{buildings} buildings · {steps} levels",
      constructionBudgetEmptySummary: "Add a building to see what the budget can cover.",
      constructionNoBudgetSummary: "No budget set · {total} upgrades planned",
      constructionBudgetAllFit: "The budget covers all {total} upgrades.",
      constructionBudgetStopsBefore: "Covers {affordable}/{total}; {building} {from}→{to} needs {count} more",
      buildingCatalog: "Building catalog",
      buildingCatalogHint: "Choose buildings to add; the picker stays open for batch planning.",
      addBuilding: "Add building",
      closeBuildingPicker: "Close building catalog",
      buildingCategoryFilter: "Building categories",
      buildingCategoryAll: "All",
      buildingCategoryCore: "Core",
      buildingCategoryLife: "Life",
      buildingCategoryCombat: "Combat",
      buildingCategoryShrine: "Shrines",
      searchBuildings: "Search buildings",
      currentLevel: "Current level",
      buildingPlanCost: "Plan cost",
      buildingEditor: "Building plan editor",
      selectBuildingPrompt: "Select a building.",
      buildingMaxLevel: "Maximum level",
      notPlanned: "Not planned",
      buildingTileLabel: "{building}, current level {current}, target {target}",
      buildingTileAddLabel: "Add {building}, current level {current}",
      buildingTileUnknownLabel: "Add {building}; enter its unknown current level first",
      buildingTilePlannedLabel: "Go to {building} in the plan, target level {target}",
      buildingTileMaxLabel: "{building} is at maximum level and cannot be added",
      currentBuildingLevelRequired: "Its current level is unavailable. Enter it before adding this building.",
      currentBuildingLevelLabel: "Current level for {building}",
      currentBuildingLevelHelp: "Enter a whole number from 0 to {max}.",
      currentBuildingLevelRange: "The current level must be a whole number from 0 to {max}.",
      addBuildingToPlan: "Add to construction plan",
      cancel: "Cancel",
      buildingAddedToPlan: "{building} added to the construction plan.",
      buildingRemovedFromPlan: "{building} removed from the construction plan.",
      buildingTargetUpdated: "{building}'s target is now level {target}.",
      buildingPlansReconciled: "Live levels adjusted {adjusted} plan(s) and removed {removed} completed plan(s).",
      addOneLevel: "Add 1 level",
      addFiveLevels: "Add 5 levels",
      removeBuildingPlan: "Remove from plan",
      movePlanUp: "Move {building} one position earlier",
      movePlanDown: "Move {building} one position later",
      constructionQueue: "Construction plan",
      constructionQueueHint: "Ordered by building; per-level costs are collapsed by default.",
      constructionQueueDragHint:
        "Drag the handles to reorder, use the earlier and later buttons, or press Alt with Up or Down.",
      dragConstructionPlan: "Reorder {building}",
      constructionQueueEmptyTitle: "Your construction plan is empty",
      constructionQueueEmpty: "Choose Add building to start planning.",
      constructionBudgetCutoff: "Budget cutoff · {count} remaining",
      constructionGroupBudgetCutoff: "Budget reaches level {level} · next level needs {count} more",
      constructionBudgetUnbudgeted: "No budget",
      constructionWithinBudget: "Within budget",
      constructionPartiallyWithinBudget: "Partially covered",
      constructionOverBudget: "Over budget",
      constructionSummary: "{buildings} building(s) · {steps} upgrade(s)",
      constructionPlanRowMeta: "Item {position} · {start}→{target} · {count} upgrade(s)",
      buildingTargetLabel: "Target level for {building}",
      increaseBuildingTarget: "Increase {building}'s target by {count} level(s)",
      expandBuildingSteps: "Expand per-level costs for {building}",
      collapseBuildingSteps: "Collapse per-level costs for {building}",
      removeBuildingFromPlan: "Remove {building} from the construction plan",
      buildingLevelsRead: "Current guild building levels loaded.",
      buildingLevelsUnknown: "Current guild building levels are unavailable. Verify each building's starting level.",
      buildingLevelsReadCompact: "Levels loaded",
      buildingLevelsUnknownCompact: "Levels unavailable",
      buildingLevelsCoverage: "Levels loaded: {known}/{total}",
      buildingLevelsPartialHint: "{unknown} building level(s) are unknown. Enter a current level before adding.",
      missingBuildingCost: "{building} is missing its level {level} cost and is excluded from the total.",
      moreConstructionActions: "More construction plan actions",
      clearBuildingPlans: "Clear construction plan",
      undoClearBuildingPlans: "Undo clear",
      copyBuildingPlan: "Copy plan",
      exportBuildingCsv: "Export CSV",
      buildingPlanCopied: "Construction plan copied.",
      buildingPlanCopyFailed: "Clipboard access failed. Use CSV export instead.",
      noBuildingMatches: "No buildings match these filters.",
      buildingPlanCleared: "Cleared {count} construction plan item(s).",
      buildingPlanRestored: "Restored {count} construction plan item(s).",
      buildingPlanReordered: "Construction order saved.",
      buildingPlanMovedToPosition: "{building} moved to item {position} of {total}.",
      constructionOrder: "Order",
      fromLevel: "From level",
      toLevel: "To level",
      stepCost: "Step cost",
      cumulativeCost: "Cumulative cost",
      buildingCsvFileName: "milky-way-idle-guild-construction-plan.csv",
      buildingGuildHall: "Guild Hall",
      buildingBuildersHall: "Builders' Hall",
      buildingArchives: "Archives",
      buildingTreasury: "Treasury",
      buildingSkillingEncampment: "Skilling Encampment",
      buildingWorkshop: "Guild Workshop",
      buildingForge: "Guild Forge",
      buildingLogShed: "Guild Log Shed",
      buildingGarden: "Guild Garden",
      buildingDairyBarn: "Guild Dairy Barn",
      buildingKitchen: "Guild Kitchen",
      buildingSewingParlor: "Guild Sewing Parlor",
      buildingBrewery: "Guild Brewery",
      buildingLibrary: "Guild Library",
      buildingLaboratory: "Guild Laboratory",
      buildingMysticalStudy: "Guild Mystical Study",
      buildingCombatEncampment: "Combat Encampment",
      buildingGym: "Guild Gym",
      buildingDojo: "Guild Dojo",
      buildingArcheryRange: "Guild Archery Range",
      buildingArmory: "Guild Armory",
      buildingDiningRoom: "Guild Dining Room",
      buildingObservatory: "Guild Observatory",
      targetCredits: "Target credits",
      marketReference: "Market price reference",
      priceReference: "Price reference",
      refreshEstimate: "Refresh market estimate",
      waitingExchangeRules: "Waiting for game exchange data...",
      guildShrineBatchPlan: "Batch plan by current guild shrine levels",
      setGuildLifeTarget: "Fill Life levels",
      setGuildCombatTarget: "Fill Combat levels",
      guildAutofillAllExcluded: "Every {domain} shrine is excluded from batch fill.",
      guildAutofillDomainExcluded: "No {domain} shrine participates in batch fill. Select one in Settings.",
      selectedUpgradePlanCount: "{count} upgrade plan(s) selected",
      addShrine: "Add shrine",
      clearAll: "Clear all",
      guideEnable: "Enable highlight guide",
      guideDisable: "Disable highlight guide",
      guideReady: "Highlight guide is ready",
      guideReadyHint: "It marks the next step from your plan and live inventory without taking actions.",
      guideNoPlans: "No shrine plan yet",
      guideNoPlansHint: "Add at least one shrine upgrade to start the guide.",
      guideLoading: "Calculating the next step",
      guideLoadingHint: "Waiting for shrine rules, inventory, or market data.",
      guideComplete: "The current plan is complete",
      guideCompleteHint: "Every target shrine has reached its planned level.",
      guideMissingCredits: "Next: fill {count} credit type(s)",
      guideMissingCreditsHint: "Choose in the Guild Shop: {items}",
      guideChooseItem: "Next: select {item}",
      guideChooseItemHint: "This is the current best exchange item for {credit}.",
      guideSetQuantity: "Next: enter {count} batches",
      guideSetQuantityHint: "Uses about {items} {item} and yields {credits} credits.",
      guideSetQuantityLimitHint: "{remaining} batches remain in total; this exchange allows up to {max}.",
      guideQuantityLabel: "Remaining for this plan",
      guideQuantityUnit: "batches",
      guideQuantityRemaining: "The current plan needs {count} more batches",
      guideQuantityCurrentExchange: "Enter {count} batches this time",
      guideTokenQuantityDetail: "Enter {batches} batches to use {items} guild tokens this time",
      guideUseGuildTokens: "Next: use {count} guild tokens",
      guideUseGuildTokensHint: "Guild-token exchange is selected for {credit}.",
      guideUnavailable: "An exchange step is unavailable",
      guideUnavailableHint:
        "No market option is available for this credit. Refresh prices or change its exchange mode.",
      guideBlocked: "Other materials are still missing",
      guideBlockedHint: "Fill these first: {items}",
      guideUpgradeShrine: "Materials are ready; upgrade the shrine",
      guideUpgradeShrineHint: "Upgrade: {shrines}",
      nativeGuildShopTab: "Shop",
      waitingUpgradeRules: "Waiting for shrine upgrade data...",
      author: "Author: 柆雨",
      support: "For help or updates, join QQ group: 437320340",
      fallbackInstaller: "Can't reach Greasy Fork? Use the fallback installer",
      noMarketEstimate: "No market price can be estimated yet",
      item: "Item",
      exchange: "Exchange",
      perCredit: "Per credit",
      targetCost: "Target cost",
      tokenExchangeValue: "{token} exchange value",
      noMarketValue: "No market estimate",
      noExchangeRules: "Exchange rules are unavailable. Refresh the game, then reopen the guild shop.",
      readingRules: "Read {count} exchange rule(s); loading the public market snapshot...",
      snapshotLoadFailed: "Market snapshot failed to load: {message}",
      credits: "credits",
      goldPerCredit: "gold / credit",
      singleExchange: "Direct exchange",
      marketCost: "Market cost",
      exchangeRecommendation: "Best exchange recommendation",
      advisorReferenceSelected: "Sell at highest bid (2% tax) · Buy at {reference}",
      advisorReference: "Buy at {reference}",
      chooseItem: "Select an exchange item to compare sell-and-buy-back options.",
      alreadyOptimal: "The current item is already optimal; selling and buying back would not help.",
      sellAndBuyMore: "Selling and buying another item yields <strong>+{count}</strong> {credit}.",
      directMore: "Exchanging directly yields <strong>{count}</strong> more {credit}.",
      sameCredits: "Both options yield the same number of credits.",
      selected: "Current item",
      selectedOptimal: "Current item (best)",
      bestItem: "Best item",
      directExchange: "Direct exchange",
      afterTax: "After tax",
      buybackExchange: "Buy-back exchange",
      purchaseCost: "Purchase cost",
      noSellPrice: "This item has no public buy price, so sell-and-buy-back cannot be estimated.",
      noAffordableReplacement:
        "Selling this quantity yields {gold} after tax, which is not enough to buy an alternative exchange item.",
      sidebarCredit: "Credits"
    }
  };

  function normalizeLocale(locale) {
    return String(locale || "")
      .toLowerCase()
      .startsWith("zh")
      ? "zh-CN"
      : "en";
  }

  function interpolate(template, values) {
    return String(template).replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key) =>
      values && values[key] !== undefined ? String(values[key]) : `{${key}}`
    );
  }

  function createLocalizer(locale) {
    const normalizedLocale = normalizeLocale(locale);
    const strings = STRINGS[normalizedLocale];
    function t(key, values) {
      return interpolate(strings[key] || STRINGS.en[key] || key, values);
    }
    function number(value, digits) {
      if (value === null || value === undefined || !Number.isFinite(value)) return "-";
      return new Intl.NumberFormat(normalizedLocale, {
        maximumFractionDigits: digits === undefined ? 0 : digits
      }).format(value);
    }
    function quantity(key, count) {
      const formatted = number(count);
      if (normalizedLocale === "zh-CN") return t(key, { count: formatted });
      const unit =
        key === "creditQuantity"
          ? Number(count) === 1
            ? "credit"
            : "credits"
          : Number(count) === 1
            ? "item"
            : "items";
      return t(key, { count: formatted, unit });
    }
    return { locale: normalizedLocale, t, number, quantity };
  }

  return { STRINGS, normalizeLocale, createLocalizer };
});
