(function (root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.MwiGuildCreditLocalization = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const STRINGS = {
    "zh-CN": {
      unknownItem: "未知物品",
      priceReferenceA: "左一",
      priceReferenceATitle: "左一：最低出售价，可立即买入",
      priceReferenceB: "右一",
      priceReferenceBTitle: "右一：最高收购价，仅作理论参考",
      marketItem: "在市场中查看{item}",
      updateChecking: "当前版本 v{current} · 最新版本：检查中...",
      updateAvailable: "当前版本 v{current} · 最新版本 v{latest} · 发现新版本",
      updateNow: "立即更新",
      updateLatest: "当前版本 v{current} · 最新版本 v{latest} · 已是最新",
      updateUnavailable: "当前版本 v{current} · 最新版本：暂时无法读取",
      shrineForce: "力量神龛",
      shrineTempo: "节奏神龛",
      shrineSpirit: "精神神龛",
      shrineRarity: "稀有神龛",
      shrineScholar: "学者神龛",
      domainLife: "生活",
      domainCombat: "战斗",
      shrineWithDomain: "{shrine}（{domain}）",
      guildTargetApplied: "已按当前公会神龛等级设定{domain}计划，共 {count} 项需要升级。",
      guildTargetComplete: "当前已达到最大等级（{domain}）。",
      plansCleared: "已清空全部神龛升级计划。",
      level: "{level} 级",
      targetButtonReady: "按每座对应公会神龛的当前等级批量设定目标",
      targetButtonMissing: "尚未读取完整的公会神龛建筑等级：{missing}",
      targetSummary: "{domain} {count}/{total}{missing}",
      targetSummaryMissing: "（未识别：{missing}）",
      shrineLevelsRead: "公会神龛等级已读取：{summaries}。",
      shrineLevelsReading: "正在读取当前公会神龛建筑等级…",
      shrine: "神龛",
      startLevel: "起始等级",
      targetLevel: "目标等级",
      removePlan: "移除此项",
      gold: "金币",
      guildTokens: "公会代币",
      noSnapshotEstimate: "未读取到公开市场快照，暂无法估算金币成本。",
      partialEstimatedCost: "预计成本（已定价部分）",
      estimatedTotalCost: "预计总成本",
      partialAfterInventory: "库存后缺口（已定价部分）",
      afterInventory: "库存后仍需",
      inventoryUnavailable: "未读取背包库存，缺口暂按 0 件库存计算。",
      noCreditPrice: "以下信用点暂无可用市场价格：{items}。",
      costSummary: "成本概览",
      inventoryAndMissing: "库存 {owned} · 缺 {missing}",
      inventory: "库存 {count}",
      inventoryNotRead: "库存未读取",
      inventoryCoveredNoExchange: "现有库存已覆盖，无需兑换",
      backpackInventory: "背包库存 {count}",
      notRead: "未读取",
      useGuildTokensForMissingCredits: "全部信用点使用公会代币",
      useGuildTokensForMissingCreditsHint: "快速选择或清除全部；也可在每张信用点卡片单独切换。",
      guildTokenCreditPlanActive: "缺少的信用点已全部按公会代币兑换计算。",
      guildTokenCreditPlanPartialActive: "已选择 {count} 种信用点按公会代币兑换计算。",
      guildTokenCreditPlanSummary: "其中 {count} 公会代币用于兑换信用点。",
      autoGuildTokenBudget: "自动兑换代币预算",
      autoGuildTokenBudgetHint: "按每枚公会代币的市场兑换价值从高到低分配。",
      autoGuildTokenBudgetAvailable: "本次最多可用 {count}",
      autoGuildTokenPlanSummary: "已按兑换价值自动分配 {count} 枚库存公会代币。",
      autoGuildTokenExchangeNeeds: "自动分配代币",
      autoGuildTokenCoverage: "覆盖 {count} 信用点",
      optimalItemCreditMode: "最优物品",
      guildTokenCreditMode: "公会代币",
      creditExchangeModeTitle: "当前使用{mode}兑换；点击切换。",
      guildTokenExchangeNeeds: "代币兑换需",
      optimalExchangeNeeds: "最优兑换需",
      exchangeRate: "{items} → {credits}",
      itemQuantity: "{count} 个",
      creditQuantity: "{count} 点",
      optimalExchangeUnavailable: "最优兑换：暂无可用市场价格",
      requiredThisTime: "本次所需",
      noGuildRules: "未读取到神龛升级规则。请刷新游戏页面后重新打开公会。",
      allBuffsMaxed: "当前所有神龛增益均已满级。",
      noUpgradeMaterials: "当前没有需要计算的神龛升级材料。",
      missingLevelCost: "缺少 {level} 级升级成本数据。",
      invalidLevels: "起始等级或目标等级无效。",
      mergedUpgradePlans: "已合并 {count} 项神龛升级的材料成本。",
      unknownCurrentLevels: "未读取当前神龛等级，已按 0 级开始；请确认或手动调整“起始等级”。",
      snapshotFailed: "公开市场快照读取失败，暂未估算金币成本。",
      panelTitle: "公会助手",
      creditValue: "信用点性价比",
      creditValueHint: "按目标数量比较公开市场成本，首项为当前最优兑换。",
      shrineUpgrade: "神龛升级",
      guildConstruction: "公会建设",
      constructionReadOnly: "管理员规划工具 · 只计算，不会执行建筑升级",
      guildPointBudget: "可用公会点数",
      budgetOptional: "留空则只计算总成本",
      plannedSpend: "计划消耗",
      remainingPoints: "预算剩余",
      overBudgetBy: "超出预算",
      buildingCategoryAll: "全部",
      buildingCategoryCore: "基础",
      buildingCategoryLife: "生活",
      buildingCategoryCombat: "战斗",
      buildingCategoryShrine: "神龛",
      searchBuildings: "搜索建筑",
      currentLevel: "当前等级",
      buildingPlanCost: "计划成本",
      addOneLevel: "加 1 级",
      addFiveLevels: "加 5 级",
      removeBuildingPlan: "移出计划",
      movePlanUp: "提前",
      movePlanDown: "延后",
      constructionQueue: "施工队列",
      constructionQueueEmpty: "设置任意建筑的目标等级后，这里会展开逐级施工顺序。",
      constructionBudgetCutoff: "预算截止线 · 剩余 {count}",
      constructionWithinBudget: "预算内",
      constructionOverBudget: "超预算",
      constructionSummary: "{buildings} 座建筑 · {steps} 次升级",
      buildingLevelsRead: "已读取当前公会建筑等级。",
      buildingLevelsUnknown: "未读取到当前公会建筑等级；请核对各建筑的起始等级。",
      buildingRulesSnapshot: "建筑费用使用内置规则快照 {version}。",
      missingBuildingCost: "{building} 缺少 {level} 级费用，未计入总成本。",
      clearBuildingPlans: "清空计划",
      copyBuildingPlan: "复制规划",
      exportBuildingCsv: "导出 CSV",
      buildingPlanCopied: "施工规划已复制。",
      buildingPlanCopyFailed: "无法写入剪贴板，请使用 CSV 导出。",
      noBuildingMatches: "没有符合筛选条件的建筑。",
      buildingPlanCleared: "已清空公会建筑规划。",
      constructionOrder: "顺序",
      fromLevel: "起始等级",
      toLevel: "目标等级",
      stepCost: "本级成本",
      cumulativeCost: "累计成本",
      buildingCsvFileName: "银河奶牛_公会建筑规划.csv",
      buildingGuildHall: "公会大厅",
      buildingBuildersHall: "建造者殿堂",
      buildingArchives: "档案馆",
      buildingTreasury: "金库",
      buildingSkillingEncampment: "生活营地",
      buildingWorkshop: "公会工作间",
      buildingForge: "公会锻造台",
      buildingLogShed: "公会木棚",
      buildingGarden: "公会花园",
      buildingDairyBarn: "公会奶牛棚",
      buildingKitchen: "公会厨房",
      buildingSewingParlor: "公会缝纫室",
      buildingBrewery: "公会冲泡坊",
      buildingLibrary: "公会图书馆",
      buildingLaboratory: "公会实验室",
      buildingMysticalStudy: "公会神秘研究室",
      buildingCombatEncampment: "战斗营地",
      buildingGym: "公会健身房",
      buildingDojo: "公会道场",
      buildingArcheryRange: "公会射箭场",
      buildingArmory: "公会军械库",
      buildingDiningRoom: "公会餐厅",
      buildingObservatory: "公会天文台",
      targetCredits: "目标信用点",
      marketReference: "市场价格参考",
      priceReference: "价格参考",
      refreshEstimate: "刷新市场估算",
      waitingExchangeRules: "等待游戏兑换数据...",
      guildShrineBatchPlan: "按当前公会神龛等级批量规划",
      setGuildLifeTarget: "填充生活等级",
      setGuildCombatTarget: "填充战斗等级",
      selectedUpgradePlanCount: "已选择 {count} 项升级计划",
      addShrine: "添加神龛",
      clearAll: "清空全部",
      waitingUpgradeRules: "等待神龛升级数据...",
      author: "作者：柆雨",
      support: "遇到问题或无法获取最新版，请加群：437320340",
      fallbackInstaller: "无法打开 Greasy Fork？使用备用分发安装",
      noMarketEstimate: "暂无可估算的市场价格",
      item: "物品",
      exchange: "兑换",
      perCredit: "每点",
      targetCost: "目标成本",
      tokenExchangeValue: "{token}兑换价值",
      noMarketValue: "暂无市场估算",
      noExchangeRules: "未读取到兑换规则。请刷新游戏页面后重新打开公会商店。",
      readingRules: "已读取 {count} 条兑换规则，正在读取公开市场快照...",
      snapshotLoadFailed: "市场快照读取失败：{message}",
      credits: "信用点",
      goldPerCredit: "金币 / 信用",
      singleExchange: "单次兑换",
      marketCost: "市场成本",
      exchangeRecommendation: "兑换最优推荐",
      advisorReferenceSelected: "卖出右一（税 2%）·买入{reference}",
      advisorReference: "买入参考{reference}",
      chooseItem: "请选择兑换物品以计算卖出后替代方案。",
      alreadyOptimal: "当前选择已是最优物品，无需卖出再回购。",
      sellAndBuyMore: "卖出后改买可多获得 <strong>+{count}</strong> {credit}。",
      directMore: "直接兑换可多获得 <strong>{count}</strong> {credit}。",
      sameCredits: "两种方案可获得相同的信用点。",
      selected: "当前选择",
      selectedOptimal: "当前选择（最优）",
      bestItem: "最优物品",
      directExchange: "直接兑换",
      afterTax: "税后所得",
      buybackExchange: "回购兑换",
      purchaseCost: "买入成本",
      noSellPrice: "当前物品暂无公开收购价，无法估算卖出后回购。",
      noAffordableReplacement: "售出当前数量后税后可得 {gold}，不足以回购其他可兑换物品。",
      sidebarCredit: "信用"
    },
    en: {
      unknownItem: "Unknown item",
      priceReferenceA: "Lowest ask",
      priceReferenceATitle: "Lowest ask: the current price to buy immediately",
      priceReferenceB: "Highest bid",
      priceReferenceBTitle: "Highest bid: a theoretical reference only",
      marketItem: "View {item} in Marketplace",
      updateChecking: "Current v{current} · Latest: checking...",
      updateAvailable: "Current v{current} · Latest v{latest} · Update available",
      updateNow: "Update now",
      updateLatest: "Current v{current} · Latest v{latest} · Up to date",
      updateUnavailable: "Current v{current} · Latest: unavailable",
      shrineForce: "Force Shrine",
      shrineTempo: "Tempo Shrine",
      shrineSpirit: "Spirit Shrine",
      shrineRarity: "Rarity Shrine",
      shrineScholar: "Scholar Shrine",
      domainLife: "Life",
      domainCombat: "Combat",
      shrineWithDomain: "{shrine} ({domain})",
      guildTargetApplied: "Set {domain} plans to the current guild shrine levels; {count} upgrade(s) are needed.",
      guildTargetComplete: "All {domain} shrines already meet their guild building levels; no extra materials are needed.",
      plansCleared: "Cleared all shrine upgrade plans.",
      level: "Lv. {level}",
      targetButtonReady: "Set every matching shrine target to its current guild level",
      targetButtonMissing: "Guild shrine building levels are incomplete: {missing}",
      targetSummary: "{domain} {count}/{total}{missing}",
      targetSummaryMissing: " (unread: {missing})",
      shrineLevelsRead: "Guild shrine levels read: {summaries}.",
      shrineLevelsReading: "Reading current guild shrine building levels…",
      shrine: "Shrine",
      startLevel: "Starting level",
      targetLevel: "Target level",
      removePlan: "Remove this plan",
      gold: "gold",
      guildTokens: "guild tokens",
      noSnapshotEstimate: "The public market snapshot is unavailable, so the gold cost cannot be estimated.",
      partialEstimatedCost: "Estimated cost (priced items only)",
      estimatedTotalCost: "Estimated total cost",
      partialAfterInventory: "After-inventory gap (priced items only)",
      afterInventory: "Still needed after inventory",
      inventoryUnavailable: "Backpack inventory is unavailable; the gap assumes you own 0 items.",
      noCreditPrice: "No usable market price for: {items}.",
      costSummary: "Cost summary",
      inventoryAndMissing: "Owned {owned} · Missing {missing}",
      inventory: "Owned {count}",
      inventoryNotRead: "Inventory unavailable",
      inventoryCoveredNoExchange: "Existing inventory covers this requirement; no exchange is needed",
      backpackInventory: "Backpack: {count}",
      notRead: "unavailable",
      useGuildTokensForMissingCredits: "Use guild tokens for every credit",
      useGuildTokensForMissingCreditsHint: "Select or clear all, or switch each credit card individually below.",
      guildTokenCreditPlanActive: "Every missing credit is calculated as a guild-token exchange.",
      guildTokenCreditPlanPartialActive: "{count} credit type(s) use guild-token exchanges.",
      guildTokenCreditPlanSummary: "{count} guild tokens are allocated to credit exchanges.",
      autoGuildTokenBudget: "Automatic token budget",
      autoGuildTokenBudgetHint: "Allocates tokens from highest to lowest current market exchange value.",
      autoGuildTokenBudgetAvailable: "Up to {count} available",
      autoGuildTokenPlanSummary: "Automatically allocated {count} inventory guild tokens by exchange value.",
      autoGuildTokenExchangeNeeds: "Auto-allocated tokens",
      autoGuildTokenCoverage: "Covers {count} credits",
      optimalItemCreditMode: "Best item",
      guildTokenCreditMode: "Guild tokens",
      creditExchangeModeTitle: "Current mode: {mode}. Click to switch.",
      guildTokenExchangeNeeds: "Tokens needed",
      optimalExchangeNeeds: "Best exchange needs",
      exchangeRate: "{items} → {credits}",
      itemQuantity: "{count} {unit}",
      creditQuantity: "{count} {unit}",
      optimalExchangeUnavailable: "Best exchange: no usable market price",
      requiredThisTime: "Needed now",
      noGuildRules: "Shrine upgrade rules are unavailable. Refresh the game, then reopen the guild.",
      allBuffsMaxed: "All shrine buffs are already at their maximum level.",
      noUpgradeMaterials: "There are no shrine upgrade materials to calculate.",
      missingLevelCost: "Missing upgrade cost data for level {level}.",
      invalidLevels: "The starting or target level is invalid.",
      mergedUpgradePlans: "Combined material costs for {count} shrine upgrade plan(s).",
      unknownCurrentLevels: "Current shrine levels are unavailable, so plans start at level 0. Please verify or adjust the starting level.",
      snapshotFailed: "The public market snapshot failed to load, so the gold cost is not estimated yet.",
      panelTitle: "Guild Assistant",
      creditValue: "Credit value",
      creditValueHint: "Compare public market costs for the target amount; the first item is the current best exchange.",
      shrineUpgrade: "Shrine upgrades",
      guildConstruction: "Guild construction",
      constructionReadOnly: "Admin planning tool · calculates only and never upgrades buildings",
      guildPointBudget: "Available guild points",
      budgetOptional: "Leave blank to calculate cost without a budget",
      plannedSpend: "Planned spend",
      remainingPoints: "Budget remaining",
      overBudgetBy: "Over budget",
      buildingCategoryAll: "All",
      buildingCategoryCore: "Core",
      buildingCategoryLife: "Life",
      buildingCategoryCombat: "Combat",
      buildingCategoryShrine: "Shrines",
      searchBuildings: "Search buildings",
      currentLevel: "Current level",
      buildingPlanCost: "Plan cost",
      addOneLevel: "Add 1 level",
      addFiveLevels: "Add 5 levels",
      removeBuildingPlan: "Remove from plan",
      movePlanUp: "Move earlier",
      movePlanDown: "Move later",
      constructionQueue: "Construction queue",
      constructionQueueEmpty: "Set a target level for any building to expand its level-by-level construction order here.",
      constructionBudgetCutoff: "Budget cutoff · {count} remaining",
      constructionWithinBudget: "Within budget",
      constructionOverBudget: "Over budget",
      constructionSummary: "{buildings} building(s) · {steps} upgrade(s)",
      buildingLevelsRead: "Current guild building levels loaded.",
      buildingLevelsUnknown: "Current guild building levels are unavailable. Verify each building's starting level.",
      buildingRulesSnapshot: "Building costs use bundled rules snapshot {version}.",
      missingBuildingCost: "{building} is missing its level {level} cost and is excluded from the total.",
      clearBuildingPlans: "Clear plan",
      copyBuildingPlan: "Copy plan",
      exportBuildingCsv: "Export CSV",
      buildingPlanCopied: "Construction plan copied.",
      buildingPlanCopyFailed: "Clipboard access failed. Use CSV export instead.",
      noBuildingMatches: "No buildings match these filters.",
      buildingPlanCleared: "Guild construction plan cleared.",
      constructionOrder: "Order",
      fromLevel: "From level",
      toLevel: "To level",
      stepCost: "Step cost",
      cumulativeCost: "Cumulative cost",
      buildingCsvFileName: "milky-way-idle-guild-construction-plan.csv",
      buildingGuildHall: "Guild Hall",
      buildingBuildersHall: "Builders' Hall",
      buildingArchives: "Archives",
      buildingTreasury: "Treasury",
      buildingSkillingEncampment: "Skilling Encampment",
      buildingWorkshop: "Guild Workshop",
      buildingForge: "Guild Forge",
      buildingLogShed: "Guild Log Shed",
      buildingGarden: "Guild Garden",
      buildingDairyBarn: "Guild Dairy Barn",
      buildingKitchen: "Guild Kitchen",
      buildingSewingParlor: "Guild Sewing Parlor",
      buildingBrewery: "Guild Brewery",
      buildingLibrary: "Guild Library",
      buildingLaboratory: "Guild Laboratory",
      buildingMysticalStudy: "Guild Mystical Study",
      buildingCombatEncampment: "Combat Encampment",
      buildingGym: "Guild Gym",
      buildingDojo: "Guild Dojo",
      buildingArcheryRange: "Guild Archery Range",
      buildingArmory: "Guild Armory",
      buildingDiningRoom: "Guild Dining Room",
      buildingObservatory: "Guild Observatory",
      targetCredits: "Target credits",
      marketReference: "Market price reference",
      priceReference: "Price reference",
      refreshEstimate: "Refresh market estimate",
      waitingExchangeRules: "Waiting for game exchange data...",
      guildShrineBatchPlan: "Batch plan by current guild shrine levels",
      setGuildLifeTarget: "Fill Life levels",
      setGuildCombatTarget: "Fill Combat levels",
      selectedUpgradePlanCount: "{count} upgrade plan(s) selected",
      addShrine: "Add shrine",
      clearAll: "Clear all",
      waitingUpgradeRules: "Waiting for shrine upgrade data...",
      author: "Author: 柆雨",
      support: "For help or updates, join QQ group: 437320340",
      fallbackInstaller: "Can't reach Greasy Fork? Use the fallback installer",
      noMarketEstimate: "No market price can be estimated yet",
      item: "Item",
      exchange: "Exchange",
      perCredit: "Per credit",
      targetCost: "Target cost",
      tokenExchangeValue: "{token} exchange value",
      noMarketValue: "No market estimate",
      noExchangeRules: "Exchange rules are unavailable. Refresh the game, then reopen the guild shop.",
      readingRules: "Read {count} exchange rule(s); loading the public market snapshot...",
      snapshotLoadFailed: "Market snapshot failed to load: {message}",
      credits: "credits",
      goldPerCredit: "gold / credit",
      singleExchange: "Direct exchange",
      marketCost: "Market cost",
      exchangeRecommendation: "Best exchange recommendation",
      advisorReferenceSelected: "Sell at highest bid (2% tax) · Buy at {reference}",
      advisorReference: "Buy at {reference}",
      chooseItem: "Select an exchange item to compare sell-and-buy-back options.",
      alreadyOptimal: "The current item is already optimal; selling and buying back would not help.",
      sellAndBuyMore: "Selling and buying another item yields <strong>+{count}</strong> {credit}.",
      directMore: "Exchanging directly yields <strong>{count}</strong> more {credit}.",
      sameCredits: "Both options yield the same number of credits.",
      selected: "Current item",
      selectedOptimal: "Current item (best)",
      bestItem: "Best item",
      directExchange: "Direct exchange",
      afterTax: "After tax",
      buybackExchange: "Buy-back exchange",
      purchaseCost: "Purchase cost",
      noSellPrice: "This item has no public buy price, so sell-and-buy-back cannot be estimated.",
      noAffordableReplacement: "Selling this quantity yields {gold} after tax, which is not enough to buy an alternative exchange item.",
      sidebarCredit: "Credits"
    }
  };

  function normalizeLocale(locale) {
    return String(locale || "").toLowerCase().startsWith("zh") ? "zh-CN" : "en";
  }

  function interpolate(template, values) {
    return String(template).replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key) => values && values[key] !== undefined ? String(values[key]) : `{${key}}`);
  }

  function createLocalizer(locale) {
    const normalizedLocale = normalizeLocale(locale);
    const strings = STRINGS[normalizedLocale];
    function t(key, values) {
      return interpolate(strings[key] || STRINGS.en[key] || key, values);
    }
    function number(value, digits) {
      if (value === null || value === undefined || !Number.isFinite(value)) return "-";
      return new Intl.NumberFormat(normalizedLocale, { maximumFractionDigits: digits === undefined ? 0 : digits }).format(value);
    }
    function quantity(key, count) {
      const formatted = number(count);
      if (normalizedLocale === "zh-CN") return t(key, { count: formatted });
      const unit = key === "creditQuantity"
        ? Number(count) === 1 ? "credit" : "credits"
        : Number(count) === 1 ? "item" : "items";
      return t(key, { count: formatted, unit });
    }
    return { locale: normalizedLocale, t, number, quantity };
  }

  return { STRINGS, normalizeLocale, createLocalizer };
});
